### PR TITLE
Create decent stacktrace with PIE code

### PR DESCRIPTION
**Pull request by dschwoerer**

### CODE REVIEW

**Comment by ZedThree** [comment]
Is this something that needs to be checked for at configure time? Or is there a reasonable expectation that `dlfcn.h` will always be available?

A quick search suggests that it's a POSIX-thing, so I'm guessing it's the latter, but I don't know anything about this.

**Comment by dschwoerer** [comment]
Checking at compile time would make sense in ether case, I suppose ...
I will write a check ...

**Comment by ZedThree** [comment]
This looks fine. Could you just give an example of the difference this makes?

**Comment by dschwoerer** [comment]
Without substraction addr2line cannot resolve anything:
```
====== Exception path ======
[bt] #1 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN13BoutExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1b1) [0x7fee651fda9f]
?? ??:0
[bt] #2 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_Z19throw_BoutExceptionNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x5b) [0x7fee65148236]
?? ??:0
[bt] #3 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0xa017c) [0x7fee6514917c]
?? ??:0
[bt] #4 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PythonModel3rhsEd+0x1d) [0x7fee651555b1]
?? ??:0
[bt] #5 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN12PhysicsModel6runRHSEd+0xa) [0x7fee6515d492]
?? ??:0
[bt] #6 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN6Solver7run_rhsEd+0xc2c) [0x7fee65166c9a]
?? ??:0
[bt] #7 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PvodeSolver3rhsEidPdS0_+0x60) [0x7fee65252cba]
?? ??:0
[bt] #8 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_Z8solver_fidPN5pvode9nvec_typeES1_Pv+0x18) [0x7fee65252d19]
?? ??:0
[bt] #9 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN5pvode11CVodeMallocEiPFvidPNS_9nvec_typeES1_PvEdS1_iiiPdS2_S2_P8_IO_FILEiPlS5_S2_+0x3d5) [0x7fee65276c3c]
?? ??:0
[bt] #10 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PvodeSolver4initEid+0x771) [0x7fee65253619]
?? ??:0
[bt] #11 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN6Solver5solveEid+0x33a) [0x7fee651677de]
?? ??:0
[bt] #12 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x80f11) [0x7fee65129f11]
?? ??:0
[bt] #13 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x7a61d) [0x7fee6512361d]
?? ??:0
[bt] #14 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x7d2a4) [0x7fee651262a4]
?? ??:0
[bt] #15 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x693d0) [0x7fee651123d0]
?? ??:0
[bt] #16 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x6b5bc) [0x7fee651145bc]
?? ??:0
[bt] #17 /lib64/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x94) [0x7fee6d04c834]
?? ??:0
[bt] #18 /lib64/libpython3.6m.so.1.0(+0x18e4ed) [0x7fee6d0bf4ed]
?? ??:0
[bt] #19 /lib64/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x34a) [0x7fee6d0ed70a]
?? ??:0
[bt] #20 /lib64/libpython3.6m.so.1.0(PyEval_EvalCodeEx+0x328) [0x7fee6d0cc588]
?? ??:0
[bt] #21 /lib64/libpython3.6m.so.1.0(PyEval_EvalCode+0x1b) [0x7fee6d0cd2fb]
?? ??:0
[bt] #22 /lib64/libpython3.6m.so.1.0(+0x221e02) [0x7fee6d152e02]
?? ??:0
[bt] #23 /lib64/libpython3.6m.so.1.0(PyRun_FileExFlags+0x9d) [0x7fee6d153acd]
?? ??:0
[bt] #24 /lib64/libpython3.6m.so.1.0(PyRun_SimpleFileExFlags+0x1b7) [0x7fee6d155637]
?? ??:0
[bt] #25 /lib64/libpython3.6m.so.1.0(Py_Main+0x6a3) [0x7fee6d156633]
?? ??:0
[bt] #26 python3(main+0x1f5) [0x562bd24f7cf5]
[bt] #27 /lib64/libc.so.6(__libc_start_main+0xea) [0x7fee6c24088a]
?? ??:0
[bt] #28 python3(_start+0x2a) [0x562bd24f7e6a]
```

With the fix, the address is resolved, and we get the function including line and source code function.
```
====== Exception path ======
[bt] #1 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN13BoutExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1b1) [0x7f95b385caf1]
BoutException::BoutException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) at path/src/sys/boutexception.cxx:131
[bt] #2 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_Z19throw_BoutExceptionNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x5b) [0x7f95b37a7296]
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const at /usr/include/c++/7/bits/basic_string.h:176
[bt] #3 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0xa01dc) [0x7f95b37a81dc]
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const at /usr/include/c++/7/bits/basic_string.h:176
[bt] #4 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PythonModel3rhsEd+0x1d) [0x7f95b37b4611]
PythonModel::rhs(double) at path/tools/pylib/_boutcore_build/helper.h:77
[bt] #5 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN12PhysicsModel6runRHSEd+0xa) [0x7f95b37bc4f2]
PhysicsModel::runRHS(double) at path/src/physics/physicsmodel.cxx:45
[bt] #6 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN6Solver7run_rhsEd+0xc2c) [0x7f95b37c5cfa]
Solver::run_rhs(double) at path/src/solver/solver.cxx:1271
[bt] #7 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PvodeSolver3rhsEidPdS0_+0x60) [0x7f95b38b1d0c]
PvodeSolver::rhs(int, double, double*, double*) at path/src/solver/impls/pvode/pvode.cxx:299
[bt] #8 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_Z8solver_fidPN5pvode9nvec_typeES1_Pv+0x18) [0x7f95b38b1d6b]
solver_f(int, double, pvode::nvec_type*, pvode::nvec_type*, void*) at path/src/solver/impls/pvode/pvode.cxx:333
[bt] #9 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN5pvode11CVodeMallocEiPFvidPNS_9nvec_typeES1_PvEdS1_iiiPdS2_S2_P8_IO_FILEiPlS5_S2_+0x3d5) [0x7f95b38d5c8e]
pvode::CVodeMalloc(int, void (*)(int, double, pvode::nvec_type*, pvode::nvec_type*, void*), double, pvode::nvec_type*, int, int, int, double*, void*, void*, _IO_FILE*, int, long*, double*, void*) at path/externalpackages/PVODE/source/cvode.cpp:642
[bt] #10 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN11PvodeSolver4initEid+0x771) [0x7f95b38b266b]
PvodeSolver::init(int, double) at path/src/solver/impls/pvode/pvode.cxx:171
[bt] #11 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(_ZN6Solver5solveEid+0x33a) [0x7f95b37c683e]
Solver::solve(int, double) at path/src/solver/solver.cxx:524
[bt] #12 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x80f71) [0x7f95b3788f71]
__pyx_pf_8boutcore_16PhysicsModelBase_2solve at path/tools/pylib/_boutcore_build/boutcore.cpp:13115
[bt] #13 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x7a67d) [0x7f95b378267d]
__Pyx_PyObject_CallMethO at path/tools/pylib/_boutcore_build/boutcore.cpp:31379
[bt] #14 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x7d304) [0x7f95b3785304]
__pyx_pf_8boutcore_12PhysicsModel_2solve at path/tools/pylib/_boutcore_build/boutcore.cpp:14401
[bt] #15 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x69430) [0x7f95b3771430]
__Pyx_CyFunction_CallMethod(_object*, _object*, _object*, _object*) at path/tools/pylib/_boutcore_build/boutcore.cpp:33604
[bt] #16 path/tools/pylib/_boutcore_build/boutcore.cpython-36m-x86_64-linux-gnu.so(+0x6b61c) [0x7f95b377361c]
__Pyx_CyFunction_Call at path/tools/pylib/_boutcore_build/boutcore.cpp:33623
[bt] #17 /lib64/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x94) [0x7f95bb6ac834]
_PyObject_FastCallDict at ??:?
[bt] #18 /lib64/libpython3.6m.so.1.0(+0x18e4ed) [0x7f95bb71f4ed]
_PyObject_CallMethod_SizeT at ??:?
[bt] #19 /lib64/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x34a) [0x7f95bb74d70a]
_PyEval_EvalFrameDefault at ??:?
[bt] #20 /lib64/libpython3.6m.so.1.0(PyEval_EvalCodeEx+0x328) [0x7f95bb72c588]
PyEval_EvalCodeEx at ??:?
[bt] #21 /lib64/libpython3.6m.so.1.0(PyEval_EvalCode+0x1b) [0x7f95bb72d2fb]
PyEval_EvalCode at ??:?
[bt] #22 /lib64/libpython3.6m.so.1.0(+0x221e02) [0x7f95bb7b2e02]
PyAST_CompileObject at ??:?
[bt] #23 /lib64/libpython3.6m.so.1.0(PyRun_FileExFlags+0x9d) [0x7f95bb7b3acd]
PyRun_FileExFlags at ??:?
[bt] #24 /lib64/libpython3.6m.so.1.0(PyRun_SimpleFileExFlags+0x1b7) [0x7f95bb7b5637]
PyRun_SimpleFileExFlags at ??:?
[bt] #25 /lib64/libpython3.6m.so.1.0(Py_Main+0x6a3) [0x7f95bb7b6633]
Py_Main at ??:?
[bt] #26 python3(main+0x1f5) [0x55af3aeb5cf5]
[bt] #27 /lib64/libc.so.6(__libc_start_main+0xea) [0x7f95ba8a088a]
__libc_start_main at ??:?
[bt] #28 python3(_start+0x2a) [0x55af3aeb5e6a]
```

**Pull request merged**
