### PR TITLE
Coloring

### PR DESCRIPTION
**Pull request by bendudson**
Adds support for algebraic constraints and finite difference Jacobian approximation using coloring to the IMEX-BDF2 solver

New example IMEX/drift-wave-constraint 

Some documentation in README.md files and the user manual

### CODE REVIEW

**Comment by d7919** [comment]
I think line 590 of imex-bdf2.cxx may need modifying to support PETSc<3.4.

**Comment by d7919** [comment]
I find that using the matrix_free=true approach leads to errors unless I specify `-pc_type` on the run line to set the preconditioner to none. I think it's possible to pass in a different matrix to SNESSetJacobian for use with preconditioning but I think probably all we want to do is set the PETSc default preconditioner to none if `matrix_free=true` and `use_precon=false || !hasUserPrecon()`. This would be around line 660 I think.

**Comment by bendudson** [comment]
Hi David,

I found it worked with preconditioning. Is this for the IMEX/diffusion-nl
and IMEX/drift-wave-constraint examples, because those were working well
for me. Is it a PETSc version issue, as I was testing with 3.4.?

Ben

**Comment by d7919** [comment]
This is actually for the gyro-fluid model that I'm working on. I'm using v3.4.5 and I'm running with `solver:matrix_free=true`, `solver:use_precon=false` and `-info` and I get the following output

~~~~
[0] PCSetUp(): Setting up new PC
[0]PETSC ERROR: --------------------- Error Message ------------------------------------
[0]PETSC ERROR: No support for this operation for this object type!
[0]PETSC ERROR: Matrix type mffd does not support getting diagonal block!
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Petsc Release Version 3.4.5, Jun, 29, 2014 
[0]PETSC ERROR: See docs/changes/index.html for recent updates.
[0]PETSC ERROR: See docs/faq.html for hints about trouble shooting.
[0]PETSC ERROR: See docs/index.html for manual pages.
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Libraries linked from src/petsc-3.4.5/arch-linux2-cxx-opt_REAL/lib
[0]PETSC ERROR: Configure run at Mon Jul 13 12:39:41 2015
[0]PETSC ERROR: Configure options  --with-clanguage=cxx --download-ptscotch --download-pastix --download-superlu_dist --download-parmetis --download-metis --download-mumps --download-hypre --download-scalapack --download-blacs --with-fftw --with-fftw-dir=/usr --with-netcdf --with-netcdf-dir=/usr --with-mpi=yes --with-precision=double --with-scalar-type=real --with-shared-libraries=0 --with-debugging=no --with-make-np=64 --COPTFLAGS="-O3 -flto=64 -fwhole-program " --CXXOPTFLAGS="-O3 -flto=64 -fwhole-program " --FOPTFLAGS=-O3
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: MatGetDiagonalBlock() line 161 in src/mat/interface/matrix.c
[0]PETSC ERROR: PCSetUp_BJacobi() line 126 in src/ksp/pc/impls/bjacobi/bjacobi.c
[0]PETSC ERROR: PCSetUp() line 890 in src/ksp/pc/interface/precon.c
[0]PETSC ERROR: KSPSetUp() line 278 in src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: KSPSolve() line 399 in src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: SNESSolve_NEWTONLS() line 220 in src/snes/impls/ls/ls.c
[0]PETSC ERROR: SNESSolve() line 3636 in src/petsc-3.4.5/src/snes/interface/snes.c

~~~~

**Comment by d7919** [comment]
Ah sorry, it looks like this was from an unclean build.

**Pull request merged**
