### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by estaremp**
Translated what was already in the .po file into Spanish. 

Will add more strings, _( ), into the file as I get an idea on how the code is structured ;)

### CODE REVIEW

**Comment by bendudson** [comment]
Cool! Thank you very much! The test failures seem to be something to do with Codecov, not the changes made here.

**Comment by ZedThree** [comment]
Coverage tests are failing because the PR is coming from a fork and codecov doesn't know it's associated with the project.

We might need to mark those tests as "allowed to fail" as everything important actually passed.

**Comment by estaremp** [comment]
Mmm...I see, I was wondering if that was the reason. 
I can just do a PR from outside my fork, that's probably the easiest.

**Comment by ZedThree** [comment]
It's not a problem, I can see that all the tests are passing! It's just I need to click one link in order to do so.

**Comment by bendudson** [comment]
Replaced by #1579

**Pull request closed without merging**
