### PR TITLE
Configure

### PR DESCRIPTION
**Pull request by dschwoerer**
Should fix issue #103

### CODE REVIEW

**Comment by ZedThree** [comment]
This looks great! I have a few comments:
The big one is that this includes GPLv3 code, but BOUT++ is released under LGPL. Including this code would require us to relicense BOUT++ as GPLv3. We might be able to contact the authors of ESPResSO and ask if we can include it as LGPL. If not, I think the stuff from ESPResSO will have to be rewritten, unfortunately.

Secondly, does this change how `./configure` should be called? i.e. can we still run `./configure --with-netcdf=/path/to/netcdf`? From what I can tell, it looks like this is the case.

Lastly, this is a minor point, but there's some whitespace changes that cause the diffs to be a little confusing, mostly starting from [configure.ac:930](https://github.com/boutproject/BOUT-dev/pull/140/files#diff-67e997bcfdac55191033d57a16d1408aR930). Is it possible to replace tabs with two spaces?

**Comment by dschwoerer** [comment]
I reimplemented the two functions.

What has been the case so far?
It can still be called with --with-netcdf=yes or --with-netcdf=/path

I also changed that if it is called with --with-netcdf=yes or --with-netcdf=/path that configure fails if it is not found, as the user has requested it.

**Comment by bendudson** [comment]
I'd like to merge these changes, but I'm not sure how to test them, since configure needs to work robustly on a large number of different systems. 

Could everyone please test this out on a couple of systems, and post a message here to say which systems it works on, and if there were any failures?

**Comment by loeiten** [comment]
# Checking on laptop
Building the same way as I do with ```master```  (that is 
```
./configure --with-checks=3 --with-track --with-debug --with-petsc=/home/mmag/petsc-3.4.5 --with-sundials
```
) yields

```
rm: cannot remove 'config-build.log': No such file or directory
Enabling all debug options
Run-time checking enabled
 -> Level 3 (Full checking + stack tracing)
Segmentation fault handling enabled

Revision ID: d338801ca406ca738207a12d6cef6cf9e8f9f957
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
Warning - PETSc has no SUNDIALS support
Warning - PETSc must have C++ support
PETSc used C++ compiler 
Using PETSc 3.4 interface
Using PETSC_DIR = /home/mmag/petsc-3.4.5
Using PETSC_ARCH = 


Searching for SUNDIALS IDA library
checking for /home/mmag/local/include/ida/ida.h... yes
checking for /home/mmag/local/include/ida/ida.h... (cached) yes
checking for /home/mmag/local/include/ida/ida_spgmr.h... yes
checking for /home/mmag/local/include/ida/ida_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... yes
checking for /home/mmag/local/include/sundials/sundials_types.h... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... yes
checking for /home/mmag/local/lib/libsundials_ida.a... yes
=> IDA solver enabled

Searching for SUNDIALS' CVODE library
checking for /home/mmag/local/include/cvode/cvode_spgmr.h... yes
checking for /home/mmag/local/include/cvode/cvode.h... yes
checking for /home/mmag/local/include/cvode/cvode_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... (cached) yes
checking for /home/mmag/local/lib/libsundials_cvode.a... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... (cached) yes
=> CVODE solver enabled

Searching for FFTW library
 -> Found fftw-wisdom executable
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for fftw3.h... ./configure: line 5863: test: too many arguments
yes
checking for libfftw3... no
configure: error: "FFTW3 is needed by BOUT++"
```
I have installed ```fftw3``` through the Linux mint distribution. Running 
```ldconfig -p | grep ".*fftw"``` 
yields

```
	libfftw3q_threads.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3q_threads.so.3
	libfftw3q_omp.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3q_omp.so.3
	libfftw3q.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3q.so.3
	libfftw3l_threads.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3l_threads.so.3
	libfftw3l_omp.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3l_omp.so.3
	libfftw3l.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3l.so.3
	libfftw3f_threads.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3f_threads.so.3
	libfftw3f_omp.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3f_omp.so.3
	libfftw3f.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3f.so.3
	libfftw3_threads.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3
	libfftw3_omp.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3
	libfftw3.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfftw3.so.3
```

# Checking on cluster

Building the same way as I do with ```master```  (that is
```./configure --with-checks=3 --with-petsc=/home/mmag/petsc-3.4.5 --with-sundials --with-netcdf=/home/mmag/local```
*) yields

*Running with ```--with-checks=no``` gives the same error

```
Run-time checking enabled
 -> Level 3 (Full checking + stack tracing)
Segmentation fault handling enabled

Revision ID: 2b97a7fe4e64c06d7af041aa07c32801fbf00bc0
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
Warning - PETSc has no SUNDIALS support
Warning - PETSc must have C++ support
PETSc used C++ compiler 
Using PETSc 3.4 interface
Using PETSC_DIR = /home/mmag/petsc-3.4.5
Using PETSC_ARCH = 


Searching for SUNDIALS IDA library
checking for /home/mmag/local/include/ida/ida.h... yes
checking for /home/mmag/local/include/ida/ida.h... (cached) yes
checking for /home/mmag/local/include/ida/ida_spgmr.h... yes
checking for /home/mmag/local/include/ida/ida_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... yes
checking for /home/mmag/local/include/sundials/sundials_types.h... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... yes
checking for /home/mmag/local/lib/libsundials_ida.a... yes
=> IDA solver enabled

Searching for SUNDIALS' CVODE library
checking for /home/mmag/local/include/cvode/cvode_spgmr.h... yes
checking for /home/mmag/local/include/cvode/cvode.h... yes
checking for /home/mmag/local/include/cvode/cvode_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... (cached) yes
checking for /home/mmag/local/lib/libsundials_cvode.a... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... (cached) yes
=> CVODE solver enabled

Searching for FFTW library
 -> Found fftw-wisdom executable
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for fftw3.h... ./configure: line 5863: test: too many arguments
yes
checking for libfftw3... no
configure: error: "FFTW3 is needed by BOUT++"
```

Running ```ldconfig -p | grep ".*fftw"``` yields
```
	libfftw3l_threads.so.3 (libc6,x86-64) => /usr/lib64/libfftw3l_threads.so.3
	libfftw3l.so.3 (libc6,x86-64) => /usr/lib64/libfftw3l.so.3
	libfftw3f_threads.so.3 (libc6,x86-64) => /usr/lib64/libfftw3f_threads.so.3
	libfftw3f.so.3 (libc6,x86-64) => /usr/lib64/libfftw3f.so.3
	libfftw3_threads.so.3 (libc6,x86-64) => /usr/lib64/libfftw3_threads.so.3
	libfftw3.so.3 (libc6,x86-64) => /usr/lib64/libfftw3.so.3
```

I've installed ```fftw``` in ```$HOME/local``` as well, and running

```
./configure --with-checks=3 --with-petsc=/home/mmag/petsc-3.4.5 --with-sundials --with-netcdf=/home/mmag/local  --with-fftw=$HOME/local
```
I again get
```
rm: cannot remove `config-build.log': No such file or directory
Run-time checking enabled
 -> Level 3 (Full checking + stack tracing)
Segmentation fault handling enabled

Revision ID: 2b97a7fe4e64c06d7af041aa07c32801fbf00bc0
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
Warning - PETSc has no SUNDIALS support
Warning - PETSc must have C++ support
PETSc used C++ compiler 
Using PETSc 3.4 interface
Using PETSC_DIR = /home/mmag/petsc-3.4.5
Using PETSC_ARCH = 


Searching for SUNDIALS IDA library
checking for /home/mmag/local/include/ida/ida.h... yes
checking for /home/mmag/local/include/ida/ida.h... (cached) yes
checking for /home/mmag/local/include/ida/ida_spgmr.h... yes
checking for /home/mmag/local/include/ida/ida_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... yes
checking for /home/mmag/local/include/sundials/sundials_types.h... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... yes
checking for /home/mmag/local/lib/libsundials_ida.a... yes
=> IDA solver enabled

Searching for SUNDIALS' CVODE library
checking for /home/mmag/local/include/cvode/cvode_spgmr.h... yes
checking for /home/mmag/local/include/cvode/cvode.h... yes
checking for /home/mmag/local/include/cvode/cvode_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... (cached) yes
checking for /home/mmag/local/lib/libsundials_cvode.a... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... (cached) yes
=> CVODE solver enabled

Searching for FFTW library
 -> Found fftw-wisdom executable
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for fftw3.h... ./configure: line 5863: test: too many arguments
yes
checking for libfftw3... no
configure: error: "FFTW3 is needed by BOUT++"
```
Only this time it runs forever.

# Suggestion
Anyway: Before pushing the new configure, maybe the user manual should be updated accordingly.

**Comment by dschwoerer** [comment]
@loeiten Thanks for the feedback. Does it now work?
I do not understand why it runs in the second case forever. Could you provide me the config.log?

Concerning the manual, I think the section in the manual should still describe configure well.

**Comment by loeiten** [comment]
Same problem, both on laptop and cluster

Somewhat same error message for both
```
rm: cannot remove 'config-build.log': No such file or directory
Run-time checking disabled
Segmentation fault handling enabled

Revision ID: 777f6d428eb778db3501cb1449efc40ce78a4392
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
/home/mmag/petsc-3.4.5/conf/rules:962: /home/mmag/petsc-3.4.5//conf/petscrules: No such file or directory
make: *** No rule to make target `/home/mmag/petsc-3.4.5//conf/petscrules'.  Stop.
Warning - PETSc has no SUNDIALS support
Warning - PETSc must have C++ support
PETSc used C++ compiler 
Using PETSc 3.4 interface
Using PETSC_DIR = /home/mmag/petsc-3.4.5
Using PETSC_ARCH = 


Searching for SUNDIALS IDA library
checking for /home/mmag/local/include/ida/ida.h... yes
checking for /home/mmag/local/include/ida/ida.h... (cached) yes
checking for /home/mmag/local/include/ida/ida_spgmr.h... yes
checking for /home/mmag/local/include/ida/ida_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... yes
checking for /home/mmag/local/include/sundials/sundials_types.h... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... yes
checking for /home/mmag/local/lib/libsundials_ida.a... yes
=> IDA solver enabled

Searching for SUNDIALS' CVODE library
checking for /home/mmag/local/include/cvode/cvode_spgmr.h... yes
checking for /home/mmag/local/include/cvode/cvode.h... yes
checking for /home/mmag/local/include/cvode/cvode_bbdpre.h... yes
checking for /home/mmag/local/include/nvector/nvector_parallel.h... (cached) yes
checking for /home/mmag/local/lib/libsundials_cvode.a... yes
checking for /home/mmag/local/lib/libsundials_nvecparallel.a... (cached) yes
=> CVODE solver enabled

Searching for FFTW library
 -> Found fftw-wisdom executable
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for fftw3.h... yes
checking for libfftw3... no
configure: error: "FFTW3 is needed by BOUT++"
```

Attached is the [log](https://github.com/boutproject/BOUT-dev/files/103685/config.zip) from the cluster (which used 45 min to run). It should be said the cluster have behaved rather slow today, but 99% of the time is spend after 

```
Searching for FFTW library
 -> Found fftw-wisdom executable
```

**Comment by dschwoerer** [comment]
It seems the error is caused by [PETSC in line 373](https://github.com/dschwoerer/BOUT-dev/blame/1f97338f6d18becdc161172cc8ecdf99b6b0ddef/configure.ac#L373)
Is PETSC_LIB ever set? If so, would it be possible to add the required flags at configure time?
I assume the same should be done for PETSC_CC_INCLUDES.

**Comment by bendudson** [comment]
I have merged this into a branch "dschwoerer-configure", and made a few small changes for PETSc and SLEPc, fixing (I think) the error Michael was seeing. I'll close this pull request and issue another for the new branch

**Pull request closed without merging**
