### PR TITLE
Documentation fix: how to build pdfs

### PR DESCRIPTION
**Pull request by dschwoerer**

### CODE REVIEW

**Comment by d7919** [comment]
I could be missing this but are the tex files actually in the repo any more? From commit https://github.com/boutproject/BOUT-dev/commit/3264b8ca6acaf700d756bae8aec7ab02c332c412#diff-3c78b35502b2693fefdfc51cba3a53a5

**Comment by bendudson** [comment]
Good point! So the "old" build target won't work any more. All that TEXDIR stuff can be removed.
https://github.com/boutproject/BOUT-dev/blob/7d6090649a732f2fe4a222ac628baea34e8628bd/manual/Makefile#L44

**Comment by ZedThree** [comment]
Already on it :)

I'll close this and submit a PR removing all that make stuff

**Comment by dschwoerer** [comment]
Sorry, apparently the text around that command had changed, sorry for not checking.

**Pull request closed without merging**
