### PR TITLE
Deprecate invert_laplace() free functions

### PR DESCRIPTION
**Pull request by johnomotani**
Addresses #1452.

### CODE REVIEW

**Comment by ZedThree** [comment]
Ah, definitely! I assumed we had already dropped all uses of them. It looks like the last one is used all over the place. We should replace all uses -- make sure there are no deprecated warnings from the library either

**Comment by johnomotani** [comment]
`invert_laplace` has also been removed from the tests. The only exception `test-laplace` which tests both a `Laplacian` object and `invert_laplace` functions, so makes sense to keep there.

Also updated the boundary conditions in `tests/MMS/elm-pb` to get the test to run: replaced the `shifted` modifier which no longer exists with `toFieldAligned` which I think does the same thing. The test is still running, so don't know if it passes yet...

**Comment by johnomotani** [comment]
The last place `invert_laplace` is used in `BOUT-dev` is in the `gyroPade0` and `gyroPade1` functions. Those functions only seem to be used in the the `gyro-gem` example and `test-gyro` test, so may not be worth updating. I guess the 'fix' would be to have a `gyroAverage` class with the `gyroPade*` functions as methods, something like
```
class gyroAverage {
public:
  gyroAverage(std::string opts_section = "gyroaverage",
              CELL_LOC location = CELL_CENTRE, Mesh* mesh_in = mesh)
              : laplace_solver(nullptr) {
    laplace_solver = Laplacian::create(Options::getRoot()->getSection(opts_section),
                                       location, mesh_in);
  }

  void setGlobalFlags(int flags) {
    laplace_solver->setGlobalFlags(flags);
  }

  void setInnerBoundaryFlags(int flags) {
    laplace_solver->setInnerBoundaryFlags(flags);
  }

  void setOuterBoundaryFlags(int flags) {
    laplace_solver->setOuterBoundaryFlags(flags);
  }

  const Field3D gyroPade0(const Field3D &f, BoutReal rho) {
    laplace_solver.setCoefA(1.);
    laplace_solver.setCoefD(-rho*rho);

    // Invert, leaving boundaries unchanged
    return laplace_solver->solve(f);
  }
  ...
private:
  Laplacian* laplace_solver;
}
```

**Comment by bendudson** [comment]
I think there's enough here to be worth merging now. We can revisit the gyroPade operators in another PR.

**Pull request merged**
