### PR TITLE
bout 4to5 script

### PR DESCRIPTION
**Pull request by dschwoerer**
replaces #488 

There is no point in changing it now.
Once we are starting to work on bout 5.0 we can run this script (and finish it before that)

### CODE REVIEW

**Comment by dschwoerer** [comment]
Should I merge the script of #888 into this one?

It shouldn't hurt to have the script before it is needed - that way it can easily be run if it is applied and merge conflicts arise (i,e. there will be no need for the cherry-pick from #888 which could cause conflicts.

**Comment by ZedThree** [comment]
That's a good idea. It would be good to develop a `bout_4_to_5` tool, similar to the `bout_3_to_4` one, for mechanical changes like this.

**Comment by dschwoerer** [comment]
Should now be rather safe:
 * It is safely possible to run the script several times
 * Checks git status and warns if not clean
 * Check if bout is already version 5 - otherwise it runs only after asking

**Comment by dschwoerer** [comment]
I have added clang-format in 4f40030 - that way we should get everything clang formatted.
I think it will be a good thing to do it within this push - as such a change will cause significant merge conflicts.
If this script is applied to all branches at a give time, there should be no issues - as the change can be applied independently.
This will allow to add a clang-format test to test-code-style, such that all code will always be nicely formatted in next.

However, I would not mind to remove this commit, as it might make it harder to detect / diagnose when something goes wrong.

**Comment by dschwoerer** [comment]
Should clang-format be removed?
Due to #1017?

Besides that, this is ready for merging ...

**Comment by dschwoerer** [comment]
Can we merge master into next, to fix this?

There are some conflicts, which I am not confident which version we want to keep ...

**Comment by ZedThree** [comment]
Yes, 4.2.2 release coming soon

**Comment by dschwoerer** [comment]
I think it is failing now because the PR is not coming from the boutproject repository.

This is ready to merge :+1:

**Comment by dschwoerer** [comment]
Once more, ready for review / merge ...

**Comment by bendudson** [comment]
Thanks @dschwoerer ! Some things will need watching and updating occasionally I guess, for example the list of header files in the script. This will be handy though when the time comes for v5.

**Comment by dschwoerer** [comment]
Can we merge this?

**Comment by bendudson** [comment]
yes, please do. Thanks!

**Comment by ZedThree** [comment]
One of the tests is still failing:

```
Creating compat headerfiles
mv: cannot stat 'comm_group.hxx': No such file or directory
```

**Comment by dschwoerer** [comment]
While I have updated the list of header file, now cython fails to compile on the updated codebase ... I will investigate ...

**Comment by dschwoerer** [comment]
Now only the code coverage fails :+1: 

The list of header files is still static, but the travis script now checks that the list is up to date, and it is easier to update, as it is a separate file ...

**Comment by dschwoerer** [comment]
Once more, conflicts resolved, and ready for review / merge ...

**Comment by dschwoerer** [comment]
Can we merge this?

**Comment by bendudson** [comment]
Yes, happy to. Does anyone understand why Travis is failing now? I tried restarting the failed tests, but this doesn't seem to have helped, and the log is not very enlightening.

**Comment by dschwoerer** [comment]
Sorry, didn't notice that an actual test was failing.

It seems netcdf.hxx has been added - I have also updated the script to include a more useful error ...

**Comment by dschwoerer** [comment]
Now the tests are passing again - except coverage.

Thanks for noting the issue @bendudson

**Comment by dschwoerer** [comment]
Ready for merging (try no 7 or so)

**Comment by dschwoerer** [comment]
Should this also go into 4.3?

**Comment by bendudson** [comment]
Replaced by #1774

**Pull request closed without merging**
