### PR TITLE
Release V4.3.1

### LINKED ISSUE #1967: Time for v4.3.1
There's 25 PRs gone into master since v.4.3.0. Any outstanding issues with master before I start the release process?

### PR DESCRIPTION
**Pull request by ZedThree**
Remaining issues/PRs: https://github.com/boutproject/BOUT-dev/milestone/11
 
Closes #1967 

# Making a New Release of BOUT++

This is checklist of things to do (in order) when making a new
release. This applies equally to both major/minor releases and bugfix
releases

- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc`
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis
    
Before merging PR:

- [x] Update locale translation files
    - `make -C locale update-all`
    - Be aware that this *will* update the timestamps and *possibly*
      reorder file paths in the .po and .pot files
- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Change version number in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`

After PR is merged:

- [ ] Make tarball: `make dist`
- [ ] Try to summarise the changes!
- [ ] Make [GitHub Release][gh_release], include change summary **NB:** tag should have
      leading `v`
- [ ] Upload tarball to GitHub Release
- [ ] Upload tarball to Zenodo and publish new version
- [ ] Email BOUT++ User Group mailing list, include change summary
- [ ] Make news post on project website, include change summary
- [ ] PR `master` into `next`

[Doxyfile]: ../manual/doxygen/Doxyfile
[Doxyfile_readthedocs]: ../manual/doxygen/Doxyfile_readthedocs
[citation]: ../CITATION.cff
[configure]: ../configure.ac
[sphinx_conf]: ../manual/sphinx/conf.py
[gcg]: https://github.com/github-changelog-generator/github-changelog-generator
[gh_release]: https://github.com/boutproject/BOUT-dev/releases/new

### CODE REVIEW

**Comment by dschwoerer** [comment]
Would it make sense to try to update the translations as part of this checklist?
I am not sure any new translations will be added, so maybe #1968 is good to merge?

**Comment by ZedThree** [comment]
Oh yes, adding it to the checklist is a good idea, thanks!

**Comment by ZedThree** [comment]
I made a small  change to `locale/makefile`: https://github.com/boutproject/BOUT-dev/commit/13b11cdd123b595d2552b08bcf631c24c879c212

Everything else in this PR is housekeeping: bump version, update authors, update DOI, update change log.

Unless there are any other things that needing fixing in master, this is ready to go!

**Comment by dschwoerer** [comment]
It seems one method was removed since 4.3.0:
```
  'method void FieldData::setBoundary(const std::string&, BoundaryOp*)'    {_ZN9FieldData11setBoundaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP10BoundaryOp}
```

Otherwise 4.3.1 is ABI compatible with 4.3.0 and we wouldn't need to change the soname.
However, currently the soname is automatically changed with each release ...

**Comment by ZedThree** [comment]
We've not put much thought into the shared builds because we've basically been exclusively statically built until quite recently, as the advice for HPC has always been to build statically. I believe Cray now links dynamically by default nowadays though.

I think I'm going to need to read up on shared libraries from a maintainer's perspective!

**Pull request merged**
