### PR TITLE
Potential fix for laplacexz

### PR DESCRIPTION
**Pull request by dschwoerer**
Not quite sure it should be `section_name` or `"laplace"`

### CODE REVIEW

**Comment by johnomotani** [comment]
I think the section name was already handled by a combination of `getType`, which  is implemented in the generic `Factory` template and gets the type from `section_name`, and the constructors handling `options == nullptr` to read the `laplacexz` section. I had a similar confusion somewhere before @ZedThree put me straight!

**Comment by dschwoerer** [comment]
Without this, `test-laplacexz` is crashing on me.

Might well be that this should be fixed some where else, but it is not working without a fix ...

**Comment by ZedThree** [comment]
Looks like the PETSc LaplaceXZ does check for `options == nullptr` but `cyclic` doesn't. Best fixed there, especially because `LaplaceXZcyclic` takes a default argument of `nullptr` for `options` anyway.

**Comment by dschwoerer** [comment]
Replaced by #2025

**Pull request closed without merging**
