### PR TITLE
Utility to convert UEDGE to BOUT++ grids

### PR DESCRIPTION
**Pull request by bendudson**
Uses a combination of code adapted from INGRID (MIT license) and Hypnotoad (GPL-3)

Tested on one SN grid and two DN grids.

### CODE REVIEW

**Comment by johnomotani** [comment]
Is this a thing we could add to hypnotoad? Even if just as a standalone script? Then we could use the CI setup to test that it at least keeps running without errors.

[I have no idea about licences, but maybe that's a thing we'd have to worry about??]

**Comment by bendudson** [comment]
Hey @johnomotani I was unsure where the best place to put this would be. Talking to Mike it sounds like B2 grids are very similar to UEDGE grids, so it may be possible to make something more general that works for both. If put into hypnotoad, might it possible to load in a mesh and reuse the hypnotoad code to generate outputs? This script currently duplicates some of that code e.g metric tensor calculation.

**Comment by ZedThree** [comment]
Getting it into hypnotoad sounds like a good idea. Would that make it possible to do the reverse conversion too?

**Comment by bendudson** [comment]
Hey @ZedThree ! The reverse conversion is probably easier, as long as we have the cell corner locations and B field components at those corners.

**Comment by johnomotani** [comment]
hypnotoad does have cell corner positions. Not sure if Bp, Bt are calculated at the cell corners already, but that should be easy to do.

**Comment by bendudson** [comment]
Closing, putting script into Hypnotoad instead https://github.com/boutproject/hypnotoad/pull/136

**Pull request closed without merging**
