### PR TITLE
Fix or delete examples

### PR DESCRIPTION
**Pull request by bendudson**
Work in progress.

Aiming to clean up the examples, to ensure that they all work. I think the number of examples should also be reduced, either by deleting them or moving them to a separate repository.

We should also have little test in each example, that at least ensures that the example builds and runs a short step.

- [x] 2Dturbulence_multigrid
- [x] 6field-simple
- [x] advdiff
- [x] advdiff2
- [x] backtrace
- [x] blob2d
- [ ] blob2d-laplacexz
- [ ] blob2d-outerloop
- [ ] boundary-conditions
- [x] boutcore
- [ ] boutpp
- [x] conducting-wall-mode
- [x] conduction
- [ ] conduction-snb
- [ ] constraints
- [x] dalf3
- [ ] eigen-box
- [ ] elm-pb
- [ ] elm-pb-outerloop
- [x] em-drift
- [ ] fci-wave
- [x] fci-wave-logn
- finite-volume
    - [ ] diffusion
    - [ ] fluid
    - [ ] test
- [x] gas-compress
- [x] gravity_reduced
- [ ] gyro-gem
- [x] hasegawa-wakatani
- [ ] hasegawa-wakatani-3d
- IMEX
    - [ ] advection-diffusion
    - [ ] advection-reaction
    - [ ] diffusion-nl
    - [ ] drift-wave
    - [ ] drift-wave-constraint
- [ ] invertable_operator
- [x] jorek-compare
- [x] lapd-drift
- [ ] laplace-petsc3d
- [ ] laplacexy
- [x] make-script
- [x] monitor
- [ ] monitor-newapi
- [x] orszag-tang
- performance
    - [ ] arithmetic
    - [ ] arithmetic_3d2d
    - [ ] bracket
    - [ ] communications
    - [ ] ddx
    - [ ] ddy
    - [ ] ddz
    - [ ] iterator
    - [ ] iterator-offsets
    - [ ] laplace
    - [ ] tuning_regionblocksize
- preconditioning
    - [ ] wave
- [x] reconnect-2field
- [x] shear-alfven-wave
- [ ] lstaggered_grid
- [ ] subsampling
- [x] tokamak-2fluid
- [x] uedge-benchmark
- [ ] wave-slab
- [x] zoidberg

### CODE REVIEW

**Comment by ZedThree** [comment]
Suggestions for deletion:

- 2Dturbulence_multigrid
  - Demonstrates a solver, could done with an input file for a different model
  - Move to separate repo?
- advdiff
  - I don't think this does what it says it does
- advdiff2
  - Same as advdiff but split over multiple files -- not necessarily a useful example?
- backtrace
  - Could just put the output in the docs?
- blob2d-laplacexz
  - Possibly squash into blob2d?
- boutcore
  - Think this has been replaced by boutpp? @dschwoerer ?
- em-drift
  - Similar model to others?
- fci-wave-logn
  - Similar to fci-wave
- laplace-petsc3d
  - Is this maybe supposed to be a test?
- monitor
  - Old API -- should delete the API as well!
- staggered_grid
  - Maybe a test?
- subsampling
  - Maybe just documentation?
- zoidberg
  - Should be in zoidberg repo?

Move to separate repos?

- 6field-simple
- dalf3
- elm-pb[-outerloop]
- gravity_reduced
- gyro-gem
- hasegawa-wakatani-3d
- jorek-compare
- lapd-drift
- reconnect-2field
- tokamak-2fluid
- uedge-benchmark

**Review by dschwoerer — APPROVED** [review]
I would vote to merge this now, and then open a new PR with more things later.

**Comment by dschwoerer** [comment]
I have a fix for fci-wave in my db-outer branch, but that will require some of my other open PRs to work ...
fci-wave has an example 'logn' - so I deleted fci-wave-logn ...

**Comment by ZedThree** [comment]
Failing test is some problem with fedora packages

**Review by ZedThree — APPROVED** [review]
I think we should go ahead a merge this. The situation is much better already

**Pull request merged**
