### PR TITLE
basic backtrace in exception

### PR DESCRIPTION
**Pull request by dschwoerer**
A possible implementation of a backtrace, see issue #121 
Before it can be pulled, I need to add a check at configure time, whether this is supported on the environment - but only if this backtrace is of interest ...

the backtrace example produces for me something like:
Initialising physics module

```
[bt] Execution path:
[bt] #1 ./backtrace() [0x420d1c]
BoutException::BoutException(char const*, ...) at ??:?
[bt] #2 ./backtrace() [0x40f423]
physics_init at .../examples/backtrace/backtrace.cxx:11
[bt] #3 /lib64/libc.so.6(__libc_start_main+0xf0) [0x7f5deca24fe0]
?? ??:0
[bt] #4 ./backtrace() [0x410965]
_start at ??:?
Failed to initialise physics. Aborting
```

Note the line number, which I think can be very useful, if the physics_init / physics_run functions are longer. Additionally, if no/not many loops in the $TARGET.cxx are, the performance penalty should be negligible, as only this file is compiled with -g to allow the line number to be printed.

### CODE REVIEW

**Comment by dschwoerer** [comment]
I updated configure.ac:
 * use enable if appropriate (track, check,debug, etc.)
 * add option to enable FPEs
 * add option to call abort in exceptions

The point of abort in exceptions is, if run inside e.g. gdb, you get to take over where the exception is thrown, check the memory etc. I found this to be quite handy, but of course can also be done by setting a breakpoint in the exception.

Right now, if an exception is thrown (with ABORT disabled) this is done quietly, i.e. no backtrace is immediately printed. I think that is consistent with the old behaviour. I am not sure this is the way it should be, as if I throw an exception in the phisics_init function, what() will not get called/printed and I need to add some effort to get the error message (which exists, but is not printed).

Are there any exception which can be properly catched? I.e. where the run can and is supposed to continue?

**Comment by ZedThree** [comment]
I'm reasonably certain all the exceptions are fatal, and the run should not continue. I think in a few cases it is possible for the run to continue, but an exception is thrown because it indicates some missing/bad configuration in the input file, so you probably don't *want* it to continue. I guess you might want to do `try {} catch {}` in your physics model though.

Also, for gdb at least, you can do `catch throw` to let gdb automatically catch exceptions (i.e. no need to set a breakpoint inside the exception). This will catch it before the stack is unwound, so you do get a backtrace.

**Comment by dschwoerer** [comment]
Thanks, putting `catch throw` in .gdbinit is probably a much better way to do it :+1: 
I didn't get the error message in the physics_init because I didn't throw the exception :flushed:

bout_error calls now BoutException - I think it doesn't make sense to maintain the code twice ...

**Comment by dschwoerer** [comment]
Should I close this?

**Comment by bendudson** [comment]
Having a backtrace and an option to catch SIGFPE seem like useful things to have

**Pull request closed without merging**
