### PR TITLE
Replace shared_ptr<?>(new ?()) with make_shared

### PR DESCRIPTION
**Pull request by d7919**
Prefer use of `make_shared` over `new` with shared_ptr constructor.

### CODE REVIEW

**Comment by d7919** [comment]
I also have a commit that replaces `std::shared_ptr<FieldGenerator>` with `FieldGeneratorPtr` everywhere that could be added to this PR but touches >10 files.

**Comment by ZedThree** [comment]
Could you add those changes just for field_factory?

**Comment by d7919** [comment]
I can do it just for the files already changed in the PR if you like (which is the majority of all occurrences).

**Comment by ZedThree** [comment]
Yep, sounds good!

**Pull request merged**
