### PR TITLE
v4.3.0 Release Candidate

### PR DESCRIPTION
**Pull request by ZedThree**
- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc`
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis

Before merging PR:

- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Change version number in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`

### CODE REVIEW

**Comment by dschwoerer** [comment]
The first checkpoint isn't fulfilled.

Please either merge or close #538.

**Comment by bendudson** [comment]
> Please either merge or close #538.

Merged **and** closed. Replaced with #1774 .

**Comment by ZedThree** [comment]
I'm afraid this is taking a long time because we've discovered a serious performance regression since v4.2.2, and we're currently trying to track it down.

**Comment by ZedThree** [comment]
Last open PR before merging is #1824. I'm sure there are still bugs and performance fixes to be done, but they will have to wait.

There were also two PRs that went into `next` after this RC was opened: #1783 and #1784. As they are the only things that went into `next` since this was opened, I'm proposing to just merge `next` straight into here without a separate PR. Any objections, please let me know before the end of the day.

After those two actions, I will push commits bumping the version number and updating the changelog, and we'll be ready to go!

**Comment by ZedThree** [comment]
This is (hopefully) a human-readable version of the changelog: https://github.com/boutproject/BOUT-dev/blob/7c291cccc9e024ec33b07c9ac37bdd6e7d995f72/change_summary.md

Please could someone give it the once over for obvious mistakes?

**Pull request merged**
