### PR TITLE
Fix typo in comments explaining algorithm of LaplaceNaulin

### PR DESCRIPTION
**Pull request by johnomotani**

### CODE REVIEW

**Comment by johnomotani** [comment]
Is there a way to skip the automatic clang-format changes? It's true some of the comment lines in `naulin_laplace.cxx` are 'too long', but they look better like that than in the reformatted version.

**Comment by ZedThree** [comment]
Yep, you can use `// clang-format off`/`// clang-format on`: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code

**Review by bendudson — DISMISSED** [review]

**Comment by ZedThree** [comment]
@johnomotani Is this just marked draft due to clang-format changing the comments? If so, I'll fix it so we can merge this

**Comment by johnomotani** [comment]
@ZedThree 
> Is this just marked draft due to clang-format changing the comments? If so, I'll fix it so we can merge this

I think so!

**Review by ZedThree — APPROVED** [review]

**Pull request merged**
