### PR TITLE
fix test-laplace-petsc3d

### PR DESCRIPTION
**Pull request by dschwoerer**
fix for part of #1981

### CODE REVIEW

**Comment by dschwoerer** [comment]
openmpi seems to also include `.` in `PATH`, however mpich doesn't.

**Comment by ZedThree** [comment]
Might also be an idea to just remove the `try ... except`? It's probably more useful to have the actual output printed and not do the rest of the tests, especially on Travis

**Comment by johnomotani** [comment]
> Might also be an idea to just remove the try ... except? It's probably more useful to have the actual output printed and not do the rest of the tests, especially on Travis

I agree. The `try...except` was useful for developing/debugging the solver, but now that the tests do all pass, and should continue to, it would be better to fail immediately if one of them fails.

**Comment by dschwoerer** [comment]
Updated.

In that case [test-communications](https://github.com/boutproject/BOUT-dev/blob/next/tests/integrated/test-communications/runtest) could also be updated to fail early and not print the errors at the end, without context

**Comment by johnomotani** [comment]
> In that case test-communications could also be updated to fail early and not print the errors at the end, without context

Done in #1983.

**Pull request merged**
