### PR TITLE
Fix SUNDIALS version guard and some deprecated function calls

### PR DESCRIPTION
**Pull request by ZedThree**
Fixes an issue with one version guard (caught versions < x.2 instead of < 3.2)

Also fixes some deprecated function calls. Turns out SUNDIALS v4 introduced a bunch of functions we should've been calling, although they were only recently actually deprecated.

There is one remaining call to a deprecated function (deprecated in 5.7):

```cpp
src/solver/impls/arkode/arkode.cxx:351:33: warning: ‘int ARKStepSetAdaptivityMethod(void*, int, int, int, realtype*)’ is deprecated: use SUNAdaptController instead [-Wdeprecated-declarations]
  351 |   if (ARKStepSetAdaptivityMethod(arkode_mem, adap_method, 1, 1, nullptr) != ARK_SUCCESS) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Unfortunately the fix is not exactly straightforward, and it's not really from the docs how to upgrade.

### CODE REVIEW

**Review by bendudson — DISMISSED** [review]
Thanks @ZedThree ! @Steven-Roberts is working on the upgrade, so we'll hopefully support SUNDIALS v7, and drop support for really old versions,

**Comment by ZedThree** [comment]
Looking at what [versions of SUNDIALS are available across OSes](https://pkgs.org/search/?q=sundials), it seems most have >= 5.0, so we could use that as our minimum version?

There's still a couple of OSes (notably Ubuntu 20 LTS) that only have SUNDIALS 3, but we do have the option to download and build SUNDIALS as part of BOUT++, so this is probably not a massive problem. There's also a couple of OSes that have separate packages for SUNDIALS 2, but I doubt this is worth continuing to support.

**Comment by Steven-Roberts** [comment]
If we support SUNDIALS 5.0, I don't think there are any extra shims or special cases we need to handle to also support 4.0. Considering that BOUT++ is currently [incompatible with SUNDIALS <4.0](https://github.com/boutproject/BOUT-dev/pull/2840) and presumably this has not caused issues with users, it seems natural to me to pick 4.0 as the new minimum version to support. Just let me know @bendudson and @ZedThree what you want to go with.

**Comment by bendudson** [comment]
Thanks @Steven-Roberts ! It sounds like >= 4.0 is a good choice for now. I wouldn't spend a lot of time on supporting older versions though: We can recommend users configure BOUT++ to download and compile a compatible SUNDIALS version.

**Comment by ZedThree** [comment]
Fixed by #2896

**Pull request closed without merging**
