### PR TITLE
Update make.config.in to support subdirs

### PR DESCRIPTION
**Pull request by dschwoerer**
Include example

Should answer question #229

### CODE REVIEW

**Comment by JensMadsen** [comment]
Hi

Thank you for doing this. However, when trying to make your example I get 

> yolen@ubuntu:~/xtradisk/numerics/BOUT-dev/examples/make_subdir$ make
>   Compiling  fuu.cxx
>   Linking sub
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
> /build/glibc-qbmteM/glibc-2.21/csu/../sysdeps/x86_64/start.S:114: undefined reference to `main'
> collect2: error: ld returned 1 exit status
> ../../../make.config:165: recipe for target 'sub' failed
> make[1]: *** [sub] Error 1
> ../../make.config:86: recipe for target 'fuu' failed
> make: *** [fuu] Error 2

Can you help?

**Comment by bendudson** [comment]
I had the same problem, but think I found the solution: You have to run
"configure" first, to update the make.config script

**Comment by JensMadsen** [comment]
That fixed my problems:-D Sorry

**Comment by dschwoerer** [comment]
Yes, otherwise sub is not recognized as specialized target, and therefore it is trying to link the module to a binary - which then fails ...

**Pull request merged**
