### PR TITLE
Remove 3-element list indexers for collect()

### PR DESCRIPTION
**Pull request by johnomotani**
Previously there was an undocumented option to pass a 3-element list `[start, end, step]` to the `tind,xind,yind,zind` arguments of `collect()`. The 3-element list used an exclusive `end`, while the 2-element form uses an inclusive `end`, which is inconsistent and potentially confusing. `step` functionality is available by passing a Python `slice` to collect. Removing the 3-element list form is a safe solution: no existing scripts will silently change their behaviour, and the provided functionality is consistent.

Replaces #1861.

### CODE REVIEW

**Comment by bendudson** [comment]
Thanks John! I think this is probably a good way forward. In future passing in a slice seems to be the easiest and most consistent way, so in 5.0 perhaps we also remove the 2-element list option?

**Comment by johnomotani** [comment]
What branch should this merge into? I've got it set to `master` at the moment, because I was originally thinking of #1861 as a 'bugfix', but maybe it should go to `next` and `v4.4.0-alpha` instead?

**Comment by ZedThree** [comment]
No strong preference, but probably 4.4

**Comment by johnomotani** [comment]
Should the change go into `next` as well? If I understand right, we won't be merging changes from 4.4 to `next`. Is the plan to remove `tools/pylib` in favour of the separate `boututils` and `boutdata` repos so the change is not needed in `next`?

**Comment by ZedThree** [comment]
My preferred plan is that we completely replace `boututils/boutdata` with `xBOUT` in `next` once it's sufficient for the library needs.

From a maintenance point of view, an immediate switch-over seems like the easiest thing, but it's not clear to me how clean that will be for users. Something to discuss next week!

**Pull request merged**
