### PR TITLE
Move boutdata and boututils to separate repo and add as submodule

### LINKED ISSUE #1347: Python tools should be packaged properly
Currently all the python tools in pylib are stored in a subdirectory of the main BOUT repository. This causes a few problems:

1) The pylib is not packaged, so it can't be installed directly by python package managers such as pip and conda. The only way to import the scripts is to add them directly to your pythonpath, but this is not encouraged python practice. 

2) Not being able to use package managers properly makes tracking dependencies harder. With a proper `setup.py` file we can issue warnings about deprecated python versions, for example.

3) Any commits to BOUT++ python tools will be mixed in with commits to the main C++ codebase, which makes the git history less clear.

4) Users who want to fork just the core code or just the analysis tools have to fork both in one go, which is wasteful.

### Solution:

The best way to improve this would be to completely separate the python tools into their own repository, which is stored under [boutproject](https://github.com/boutproject), similar to the way [CHERAB](https://github.com/cherab) does it.

This repo could then by structured properly as a python package, with an informative `setup.py`, `__init__.py`'s, and a directory structure following the [recommended patterns](https://docs.python-guide.org/writing/structure/). 

Migrating all the python files to a new repo would be a breaking change in the sense that user's `$PYTHONPATH`s would no longer point to the right place, but it would not be hard to fix.

If we wanted then this package could then be uploaded to PYPI or Conda, or we could also just show people how to use pip or conda to install from their cloned source files directly. (or let them keep just adding the root directory to their pythonpaths)

Ideally the tools for each language (MATLAB etc.) would be placed in their own repo too, but it's most important to do it for python because it should be structured as a separate pure python package.

### PR DESCRIPTION
**Pull request by loeiten**
This is the continuation of #1708, with the following differences:

1. The base branch now follows the [latest commit `BOUT-dev/next`](https://github.com/boutproject/BOUT-dev/commit/50e3b46b2bea4a8c207aeb7bfe9b42b89baa7969)
2. Only `boutdata` and `boututils` have been converted to submodules

Although #1708 was tagged with 5.0 one can consider if it is better update the submodules as updates are made to [`boututils`](https://github.com/boutproject/boututils) and [`boutdata`](https://github.com/boutproject/boutdata) and replace the submodules for pip installs at 5.0 instead. In this way, I think duplicated work is minimised, and the risk of diverging repos are kept to a minimum.

This closes #1347

### CODE REVIEW

**Comment by loeiten** [comment]
This fails as the submodules now have an additional directory layer, meaning that what was `tools/pylib/boutdata` now becomes `tools/pylib/boutdata/boutdata`.

As the submodules are packaged, I suggest to remove them and add a pip install in `.travis.yml` and update the text after `configure` from "Add this to python path" to "Install these packages". Does this sound like a good idea @ZedThree and @TomNicholas?

**Comment by dschwoerer** [comment]
Possible workaround: move the submodules somewhere else, and provide compat symlinks.

**Comment by loeiten** [comment]
That is a possible workaround :). However, would we still like to have these files in the repo as they now can be obtained as packages?

**Comment by loeiten** [comment]
Closed due to https://github.com/boutproject/BOUT-dev/issues/1347#issuecomment-602747944

**Pull request closed without merging**
