### PR TITLE
Update boutdata and boututils submodules

### PR DESCRIPTION
**Pull request by dschwoerer**
boututils has been merged into the boutdata project. As such we can remove the boututuils submodule and update the compat symlinks.

Replaces #2956

### CODE REVIEW

**Comment by dschwoerer** [comment]
Do we want these updates also in v5.1.1?
I think the .tar.gz we release contains the submodules, so that would make sense, but I am not sure whether we should test the merge a bit more?

**Comment by ZedThree** [comment]
Yes, I think 5.1.1 is appropriate. Assuming the tests actually pass, I think that's good enough

**Comment by dschwoerer** [comment]
I have rebased to the rc and force-pushed, now all tests are passing :+1:

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
Thanks @dschwoerer !

**Pull request merged**
