### PR TITLE
D Schwoerer's configure improvements

### PR DESCRIPTION
**Pull request by bendudson**
Fixed PETSc configure problems, caused errors on York's "snake" machine.

Now compiles on my machine, York servers, and Archer. Could everyone please try this branch on their machines?

### CODE REVIEW

**Comment by loeiten** [comment]
The configure now works on both my laptop and on the cluster, and fixes the problems mentioned in #140.

Issue #103 is still a problem though. In some distro packages, ```libfftw``` is located in ```/usr/lib/x86_64-linux-gnu```, and as far as I see this is not a search path. The error message I get when building with

```
./configure --with-checks=3 --with-track --with-debug --with-petsc=$HOME/petsc-3.4.5 --with-sundials
```

is

```
Searching for FFTW library
 -> Path not given. Searching for library...
 -> Found fftw-wisdom executable
checking for /usr/include/fftw3.h... yes
checking for /usr/lib/libfftw3.a... no
checking for /usr/lib64/libfftw3.a... no
checking for /usr/lib/libfftw3.so... no
checking for /usr/lib64/libfftw3.so... no
ERROR: FFTW not found. Required by BOUT++
```

**Comment by dschwoerer** [comment]
What os/version are you using?

I couldn't find any, that causes this behaviour.

I found a bug, I only looked for $prefix/x86_64-linux-gnu , not $prefix/lib/x86_64-linux-gnu.

Still, if it is installed with apt-get (or similar), it should be in the default searchpath, and this should not be needed.

Secondly, I am puzzled, as configure should not look for these files. It should try to link with them, i.e. only the linker should look for them.

Finaly, the error message in the configure.ac is:
AC_MSG_ERROR('FFTW3 is needed by BOUT++') - not 'FFTW not found. Required by BOUT++'. - I can't find this error string in the configure - are you using the most recent version?
If so, could you provide me e.g. the config.log?
What distro / version are you using?

I am really confused and would like help to fix this issue.

**Comment by loeiten** [comment]
So, I'm using ```Linux Mint 17 'Qiana' MATE 64-bit```.

I tried to build ```BOUT++``` with the package
```libfftw3-bin version:3.3.3-7ubuntu3``` (I also tried installing ```libfftw3-dev``` with the same version, but it gives the same error).

The FFTW3 package was installed through the software manager (equivalent to ```sudo apt-get install``` AFAIK).

The error message above was a copy paste from the mentioned issue, sorry about that. The current error message is:

```
Searching for FFTW library
 -> Found fftw-wisdom executable
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for fftw3.h... yes
checking for libfftw3... no
configure: error: "FFTW3 is needed by BOUT++"
```

The [config.log](https://github.com/boutproject/BOUT-dev/files/150159/config.log.txt) (renamed to ```config.log.txt``` to make it easier to share with github).

Hope this helps :)

**Comment by loeiten** [comment]
Oh dear....I managed to pull the wrong version (by using git's ```command line instruction``` ```Step 1```). I've pulled the correct version, and it builds both on my laptop and on the cluster. 

My complaints above are to be ignored. Sorry for the inconvenience.

**Pull request merged**
