### PR TITLE
MPI wrapper class

### PR DESCRIPTION
**Pull request by cmacmackin**
I created a separate pull request for the refactoring of the MPI wrapper requested in PR #1803. I originally added some MPI wrapper methods to BoutMesh. These could be overridden in subclasses used for unit testing, allowing parallel-communication to be simulated on a single processor. @ZedThree suggested that they didn't really belong there and would be better off in their own class. As this requires quite a significant refactor to large portions of the code, I decided to make it a separate PR. However, this PR still contains the PETSc interface which I've submitted in PR #1805, as this is what the MPI wrapper was created for and demonstrates its use for testing. As such, it would be best that it is merged into `next` only after PR #1805.

I have created a new class called `MpiWrapper` and define a global instance of it `bout::globals::mpi`. Its member methods simply forward calls onto PETSc routines and have exactly the same interface. All MPI calls throughout the code now use the methods on the global object (or, in the case of meshes, on a pointer to the global object which I defined for convenience and brevity). The global `MpiWrapper` object is created and destroyed in `BoutInitialise()` and `BoutFinalise()`, respectively.

### CODE REVIEW

**Comment by cmacmackin** [comment]
@ZedThree These changes are ready for review. The CI fails on the CMake build which now runs two tests which previously were not routine run: `test-petsc-laplace` and `test-petsc-laplace-MAST-grid`. It appears that these tests always fail including in the `next` branch itself, as reported in Issue #1850.

**Comment by ZedThree** [comment]
Thanks @cmacmackin ! Looks like the simplest way to get this done, and now gives us the opportunity to mock out MPI calls in the tests, which I am unreasonably excited about! :tada:

I'm going to wait till #1859 goes in before merging this.

**Comment by cmacmackin** [comment]
@ZedThree Unfortunately, I've merged this branch into #1859. I will be the first to admit that was not the best idea (I did it without thinking) but at this point it would be quite difficult to reverse it I think. So probably best if this does get merged in first.

**Comment by d7919** [comment]
@cmacmackin at least on github it doesn't look like #1859 includes any of this, so perhaps you didn't push?

**Comment by cmacmackin** [comment]
@d7919 That's right, the changes are still local to my machine. Should be pushing soon, once I iron out a few more things with integration tests.

**Pull request merged**
