### PR TITLE
Fix LaplacePetsc3dAmg

### LINKED ISSUE #2225: test-laplace-petsc3d possibly broken?
The `data_circular_core` and `data_circular_core-sol` test cases have `mesh:paralleltransform = shiftedinterp`, but the option is now called `mesh:paralleltransform:type`, so they end up using the identity transform -- this passes. Making it actually use the shiftedinterp transform fails:

```
KSPConvergedReason is -9
terminate called after throwing an instance of 'BoutException'
  what():  Petsc3dAmg: inversion failed to converge.
```

which is `KSP_DIVERGED_NANORINF (residual norm became Not-a-number or Inf likely due to 0/0)`.

Possibly related is that the `data_slab_core` case doesn't seem to use one of the PETSc options:

```
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There is one unused database option. It is:
Option left: name:-boutpetsclib_laplace_mg_levels_ksp_max_it value: 3
```

This is supposed to set the number of pre- and post-smoothing steps, and is required because at some point PETSc "fixed" this option and the default value now does one less step than before, changing the error convergence.

### PR DESCRIPTION
**Pull request by johnomotani**
The bug in `test-laplace-petsc3d that @ZedThree found (#2225) was hiding a couple of other bugs in `ZInterpolation` and `ZHermiteSpline` that made the matrix for 3d Laplace_perp inversion incorrect with non-trivial parallel derivatives. These bugs should be fixed by this PR.

I've also added some extra checks (when `CHECK > 2`) for finiteness of matrix elements and interpolation weights, and bounds of indices passed to `getWeightsForYApproximation()`, which helped to find the bugs.

Fixes #2225.

### CODE REVIEW

**Comment by johnomotani** [comment]
Only the Fedora tests are failing, but they're only failing on the test that this PR is supposed to fix. It says a PETSc matrix element argument was out of range, but I've tested with PETSC-3.14.4 (same version as Fedora) and an identical `./configure --with-petsc --enable-shared` (except I passed a path for petsc) and the test passes. @ZedThree @dschwoerer should I worry about the failure?

**Comment by ZedThree** [comment]
It is a bit concerning, and I'd prefer to fix it if at all possible. I'll see if I can reproduce it locally.

**Comment by dschwoerer** [comment]
I can reproduce it using the fedora packages.

petsc is compiled with:
```
%global petsc_mpibuild_options \\\
 %if %{with debug} \
 CFLAGS="-O0 -g -Wl,-z,now -fPIC" CXXFLAGS="-O0 -g -Wl,-z,now -fPIC" FFLAGS="-O0 -g -Wl,-z,now -fPIC -I${MPI_FORTRAN_MOD_DIR}" COPTFLAGS="-O0 -g -Wl,-z,now" \\\
  CXXOPTFLAGS="-O0 -g -Wl,-z,now" FOPTFLAGS="-O0 -g -Wl,-z,now -I${MPI_FORTRAN_MOD_DIR}" LDFLAGS="$LDFLAGS -fPIC" \\\
  FCFLAGS="-O0 -g -Wl,-z,now -fPIC -I${MPI_FORTRAN_MOD_DIR}" \\\
 %else \
 CFLAGS="$CFLAGS -O3 -fPIC" CXXFLAGS="$CXXFLAGS -O3 -fPIC" FFLAGS="$FFLAGS -O3 -fPIC" LDFLAGS="$LDFLAGS -fPIC" \\\
  COPTFLAGS="$CFLAGS" CXXOPTFLAGS="$CXXFLAGS" FOPTFLAGS="$FFLAGS" \\\
  FCFLAGS="$FFLAGS -O3 -fPIC" \\\
 %endif \
  --CC_LINKER_FLAGS="$LDFLAGS" \\\
  --with-default-arch=0 --with-make=1 \\\
  --with-cmake-exec=%{_bindir}/cmake3 --with-ctest-exec=%{_bindir}/ctest3 \\\
  --with-single-library=1 \\\
  --with-precision=double \\\
  --with-petsc-arch=%{_arch} \\\
  --with-clanguage=C \\\
  --with-shared-libraries=1 \\\
  --with-fortran-interfaces=1 \\\
  --with-windows-graphics=0 \\\
  --with-cc=${MPI_BIN}/mpicc \\\
  --with-cxx=${MPI_BIN}/mpicxx \\\
  --with-fc=${MPI_BIN}/mpif90 \\\
  --with-shared-ld=ld \\\
  --with-pic=1 \\\
  --with-clib-autodetect=0 \\\
  --with-fortranlib-autodetect=0 \\\
  --with-mkl_sparse=0 \\\
  --with-mkl_sparse_optimize=0 \\\
  --with-mkl_cpardiso=0 \\\
  --with-mkl_pardiso=0 \\\
  --DATAFILESPATH=share/petsc/datafiles \\\
 %if %{with python} \
  --with-python=1 \\\
  --with-python-exec=%{__python3} \\\
  --download-petsc4py=1 \\\
 %endif \
 %if 0%{?fedora} \
  --with-cxxlib-autodetect=0 \\\
 %endif \
  --with-threadsafety=0 --with-log=1 \\\
 %if %{with debug} \
  --with-debugging=1 \\\
    --with-mpiexec="${MPI_BIN}/mpiexec -n `getconf _NPROCESSORS_ONLN` --mca btl_base_warn_component_unused 0 --mca orte_base_help_aggregate 0" \\\
 %else \
  --with-debugging=0 \\\
    --with-mpiexec="${MPI_BIN}/mpiexec -n `getconf _NPROCESSORS_ONLN` --mca btl_base_warn_component_unused 0" \\\
 %endif \
 %if %{with scalapack} \
  --with-scalapack=1 \\\
  --with-scalapack-lib="-L$MPI_LIB -lscalapack" \\\
  --with-scalapck-include="" \\\
 %endif \
 %if %{with mpi} \
  --with-mpi=1 \\\
 %endif \
 %if %{with cgns} \
  --with-cgns=1 \\\
  --with-cgns-include= \\\
  --with-cgns-lib=-lcgns \\\
 %endif \
 %if %{with hdf5} \
  --with-hdf5=1 \\\
  --with-hdf5-include= \\\
  --with-hdf5-lib="-L$MPI_LIB -lhdf5 -lhdf5_hl" \\\
 %endif \
 %if %{with ptscotch} \
  --with-ptscotch=1 \\\
  --with-ptscotch-include= \\\
  --with-ptscotch-lib="-L$MPI_LIB -lptscotch -lscotch -lptscotcherr -lscotcherr" \\\
 %endif \
 %if %{with mumps} \
  --with-mumps=1 \\\
 %endif \
 %if %{with sundials} \
  --with-sundials=1 \\\
  --with-sundials-include=$MPI_INCLUDE \\\
  --with-sundials-lib=-lsundials_nvecparallel \\\
 %endif \
 %if %{with superludist} \
  --with-superlu_dist=1 \\\
  --with-superlu_dist-include=$MPI_INCLUDE/superlu_dist \\\
  --with-superlu_dist-lib=-lsuperlu_dist \\\
 %endif \
  --with-x=1 \\\
  --with-openmp=0 \\\
  --with-hwloc=0 \\\
  --with-ssl=0 \\\
 %if %{with hypre} \
  --with-hypre=1 \\\
  --with-hypre-include=$MPI_INCLUDE/hypre \\\
  --with-hypre-lib="-L$MPI_LIB -lHYPRE" \\\
 %endif \
 %if %{with fftw} \
  --with-fftw=1 \\\
  --with-fftw-include= \\\
  --with-fftw-lib="-L$MPI_LIB -lfftw3_mpi -lfftw3" \\\
 %endif \
  --with-pthread=1 \\\
  --with-valgrind=1
```

(among some other options)

**Comment by ZedThree** [comment]
I finally managed to reproduce it by compiling with optimisations, the debug build doesn't fail. Unfortunately, this means the debugger is not much help, as lots of stuff has been inlined and otherwise rearranged. Here's the (abridged) output with some extra debugging stuff put in:

```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Argument out of range
[0]PETSC ERROR: New nonzero at (2016,2) caused a malloc
Use MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE) to turn off this check
<snip>
[0]PETSC ERROR: #1 MatSetValues_MPIAIJ() line 606 in /builddir/build/BUILD/petsc-3.14.4/buildopenmpi_dir/src/mat/impls/aij/mpi/mpiaij.c
[0]PETSC ERROR: #2 MatSetValues() line 1395 in /builddir/build/BUILD/petsc-3.14.4/buildopenmpi_dir/src/mat/interface/matrix.c
terminate called after throwing an instance of 'BoutException'
  what():  ====== Exception path ======
<snip>
[bt] #6 ./test-laplace3d() [0x40e91f]
main at /home/test/tmp/tests/integrated/test-laplace-petsc3d/test-laplace3d.cxx:117
[bt] #5 <snip> invert/laplace/impls/petsc3damg/petsc3damg.cxx:184
[bt] #4 <snip> LaplacePetsc3dAmg::updateMatrix3D() at /home/test/tmp/src/invert/laplace/impls/petsc3damg/petsc3damg.cxx:351
[bt] #3 <snip> PetscMatrix<Field3D>::Element::operator=(double) at include/bout/petsc_interface.hxx:625
[bt] #2 <snip> PetscMatrix<Field3D>::Element::setValues(double, InsertMode) at include/bout/petsc_interface.hxx:657 
[bt] #1 <snip> include/bout/../boutexception.hxx:28
====== Back trace ======
 -> PetscMatrix setting values at (2016, 0) on line 647 of '../../../../../include/bout/petsc_interface.hxx'
 -> PetscMatrix<T>::Element& PetscMatrix<T>::Element::operator=(BoutReal) [with T = Field3D; BoutReal = double] on line 625 of '../../../../../include/bout/petsc_interface.hxx'
 -> virtual Field3D LaplacePetsc3dAmg::solve(const Field3D&, const Field3D&) on line 181 of 'petsc3damg.cxx'
```

The code that's causing the problem is:

```cpp
    const int yup = (l.y() == localmesh->yend && upperY.intersects(l.x())) ? -1 : 0,
              ydown = (l.y() == localmesh->ystart && lowerY.intersects(l.x())) ? -1 : 0;
    operator3D.yup(yup)(l, l.yp()) = 0.0;
    operator3D.ydown(ydown)(l, l.ym()) = 0.0;
    operator3D.yup(yup)(l, l.xp().yp()) = 0.0;
    operator3D.ydown(ydown)(l, l.xp().ym()) = 0.0;
    operator3D.yup(yup)(l, l.xm().yp()) = 0.0;    // <---- this line
    operator3D.ydown(ydown)(l, l.xm().ym()) = 0.0;
    operator3D.yup(yup)(l, l.yp().zp()) = 0.0;
    operator3D.yup(yup)(l, l.yp().zm()) = 0.0;
    operator3D.ydown(ydown)(l, l.ym().zp()) = 0.0;
    operator3D.ydown(ydown)(l, l.ym().zm()) = 0.0;
  }
  operator3D.partialAssemble();
```

which is a bit confusing, because we clearly haven't assembled the matrix yet, so I don't know why it would complain about mallocs. We do call `MatMPIAIJSetPreallocation` when creating the `PetscMatrix`, so maybe that's getting the information wrong?

I'm going to try using ASAN/valgrind, see either of them get anywhere

**Comment by johnomotani** [comment]
That's bizzare - the preallocation and matrix elements that we set must be the same as in builds that are not raising errors?!? I'd not thought of the debugging mode in PETSc, everything I've tested has been with optimized PETSc builds. @ZedThree what configure command did you use exactly to reproduce the error?

**Comment by ZedThree** [comment]
This is my PETSc configure command:

```
./configure --prefix=/home/peter/Tools/petsc/installed/3.14.4 \
  --with-shared-libraries=1 --with-make-np=12 --with-clean=1 \
  --with-fortran-bindings=0 --download-hypre=yes \
  --download-superlu_dist=yes --with-debugging=1 \
  --with-threadsafety=0 --with-log=1 --with-mpi=1 --with-openmp=0
```

and BOUT++:

```
cmake . -B build_petsc3144 \
  -DBOUT_USE_PETSC=on -DPETSC_DIR=/home/peter/Tools/petsc/installed/3.14.4 \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja \
  -DPython_EXECUTABLE=$(which python3) \
&& cmake --build build_petsc3144/ --target test-laplace-petsc3d
```

This diff:

```diff
diff --git a/include/bout/petsc_interface.hxx b/include/bout/petsc_interface.hxx
index 1d1f3dfdf..a44fe5ea1 100644
--- a/include/bout/petsc_interface.hxx
+++ b/include/bout/petsc_interface.hxx
@@ -617,16 +617,19 @@ public:
       }
     }
     Element& operator=(const Element& other) {
+      AUTO_TRACE();
       ASSERT3(finite(static_cast<BoutReal>(other)));
       return *this = static_cast<BoutReal>(other);
     }
     Element& operator=(BoutReal val) {
+      AUTO_TRACE();
       ASSERT3(finite(val));
       value = val;
       setValues(val, INSERT_VALUES);
       return *this;
     }
     Element& operator+=(BoutReal val) {
+      AUTO_TRACE();
       ASSERT3(finite(val));
       auto columnPosition = std::find(positions.begin(), positions.end(), petscCol);
       if (columnPosition != positions.end()) {
@@ -641,10 +644,12 @@ public:
 
   private:
     void setValues(BoutReal val, InsertMode mode) {
+      TRACE("PetscMatrix setting values at ({}, {})", petscRow, petscCol);
       ASSERT3(positions.size() > 0);
       std::vector<PetscScalar> values;
       std::transform(weights.begin(), weights.end(), std::back_inserter(values),
                      [&val](BoutReal weight) -> PetscScalar { return weight * val; });
+
       int status;
       BOUT_OMP(critical)
       status = MatSetValues(*petscMatrix, 1, &petscRow, positions.size(),
@@ -724,7 +729,7 @@ public:
     BOUT_OMP(critical)
     status = MatGetValues(*get(), 1, &global1, 1, &global2, &value);
     if (status != 0) {
-      throw BoutException("Error when setting elements of a PETSc matrix.");
+      throw BoutException("Error when getting elements of a PETSc matrix.");
     }
     return value;
   }
diff --git a/src/invert/laplace/impls/petsc3damg/petsc3damg.cxx b/src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
index fdb65599a..a8a60387d 100644
--- a/src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
+++ b/src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
@@ -178,6 +178,7 @@ LaplacePetsc3dAmg::~LaplacePetsc3dAmg() {
 
 
 Field3D LaplacePetsc3dAmg::solve(const Field3D &b_in, const Field3D &x0) {
+  AUTO_TRACE();
   // If necessary, update the values in the matrix operator and initialise
   // the Krylov solver
   if (updateRequired) updateMatrix3D();
```

and using `export BOUT_SHOW_BACKTRACE=1` to get a backtrace out of the test

valgrind had a ton of output, but all leaks, rather than invalid read/writes.

**Comment by ZedThree** [comment]
AddressSanitizer to the rescue! Fix incoming

**Comment by ZedThree** [comment]
Fix was basically a single character:

```diff
modified   src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
@@ -511,7 +511,7 @@ OperatorStencil<Ind3D> LaplacePetsc3dAmg::getStencil(Mesh* localmesh,
   // If there is a lower y-boundary then create a part of the stencil
   // for cells immediately adjacent to it.
   if (lowerYBound.max() - lowerYBound.min() > 0) {
-    stencil.add([index = localmesh->ystart, &lowerYBound](Ind3D ind) -> bool {
+    stencil.add([index = localmesh->ystart, lowerYBound](Ind3D ind) -> bool {
 		  return index == ind.y() && lowerYBound.intersects(ind.x()); },
       lowerEdgeStencilVector);
   }
@@ -519,7 +519,7 @@ OperatorStencil<Ind3D> LaplacePetsc3dAmg::getStencil(Mesh* localmesh,
   // If there is an upper y-boundary then create a part of the stencil
   // for cells immediately adjacent to it.
   if (upperYBound.max() - upperYBound.min() > 0) {
-    stencil.add([index = localmesh->yend, &upperYBound](Ind3D ind) -> bool {
+    stencil.add([index = localmesh->yend, upperYBound](Ind3D ind) -> bool {
 		  return index == ind.y() && upperYBound.intersects(ind.x()); },
       upperEdgeStencilVector);
   }
```

Basically the stencil test function was capturing the `RangeIterator` by reference -- but the function took them by value, so this turned out to be taking a reference to a local variable, which of course went out of scope by the time the lambda was called in calculating the number of off-diagonals. Which explains why PETSc was complaining -- I suspect we preallocated zero off-diagonals.

I'm not sure why this worked in all the other builds!

**Review by ZedThree — APPROVED** [review]

**Comment by johnomotani** [comment]
Thanks @ZedThree! Fix looks good to me.

**Comment by ZedThree** [comment]
`test-drift-instability-staggered` timing out in the debug build again -- unrelated to this PR, so I'll merge. Needs sorting out though, so that is a task for the rest of the week

**Pull request merged**
