### PR TITLE
Update SUNDIALS support (rebase onto next)

### PR DESCRIPTION
**Pull request by ZedThree**
Replaces #2885 (rebased that branch onto `next`)

### CODE REVIEW

**Review by bendudson — DISMISSED** [review]
Thanks @ZedThree !

**Comment by Steven-Roberts** [comment]
Yes, much appreciated @ZedThree!

**Comment by Steven-Roberts** [comment]
Is there anything that still needs to be done before merging this PR? From my side, it's ready.

**Review by dschwoerer — APPROVED** [review]
@ZedThree or @bendudson do you want to merge?

**Comment by ZedThree** [comment]
I'm just going to sort out the clang-tidy warnings, then it can go in. I'll do that now

**Comment by ZedThree** [comment]
Ok, should be minimal warnings now. Good to go in as soon as tests pass

**Review by dschwoerer — APPROVED** [review]

**Comment by ZedThree** [comment]
Ah, missed one warning, never mind

**Comment by dschwoerer** [comment]
Fedora is planning to update sundials to v7:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/CK3E237FB45ZVKRCLST76A3APYIVFZYJ/

It would be nice to either release a BOUT++ v6 or backport to master and release that. Any preferences @ZedThree?

**Comment by ZedThree** [comment]
If `abicheck` says it's fine, probably easiest to just release next as 5.2, otherwise backport to master

**Comment by dschwoerer** [comment]
Abicheck says there are over 200 deleted symbols - this is caused by everything we expose being part of the public ABI.
So we need to bump soname. I think that is fine.

The question is to what extend the API changed, I see some changes related to the parallel boundaries in the abidiff, but I am not sure there is an easy way to check for API differences. I think the changes are OK, as if we wanted to preserve API/ABI we should limit the interface a lot. That would make also many changes much easier. But who has time to drive such a change?

[Here is the full abidiff output](https://github.com/user-attachments/files/15531730/abidiff.log)

**Pull request merged**
