### PR TITLE
Manual fix

### PR DESCRIPTION
**Pull request by dschwoerer**
+ fixes from master into next

### CODE REVIEW

**Comment by dschwoerer** [comment]
yes, but the fixes should anyway be in next, as they are (important) bug fixes.

It wasn't really intentionally, but I think they should be in next anyway, so I don't see any need to rebase.

If you shouldn't like the mixes, I can open a second PR, just for the bug fixes ...

**Comment by ZedThree** [comment]
4.1.1 will hopefully be out today, and then I'll merge master into next. You can wait till then and just rebase this if you like

**Comment by dschwoerer** [comment]
I thought fixes could be merged immediately into next (as it is used for production runs), but I don't mind waiting a bit ...

**Comment by ZedThree** [comment]
Are the changes in this PR just in cab3722? If so, feel free to add that commit to #722.

**Comment by dschwoerer** [comment]
Yes, that is the only new one.

I don't mind having that sit around or being ignored - what I don't get is why there should be any issues with merging master into next?
Why should I not benefit from the fixes in master?
I know, this has been discussed before, but it still seems very confusing to me, why I should manually merge, or produce potentially wrong results.

**Comment by d7919** [comment]
_This is just my understanding and this may not be policy._
I think the idea is that tagged releases are what should be used for any science production -- using anything else, such as next, may be possible but it is not a promise. In practice we do/should try to get bug fixes into next reasonably regularly so that using next is usually not a problem (i.e. no known fatal bugs), but rather than doing it with each individual bug fix we update when there's an update to the tagged release (then available in master). This way next can be thought of as "tagged release PLUS new features MINUS old features" rather than "current master PLUS new features MINUS old features".

**Comment by dschwoerer** [comment]
I think there are benefits of fixing bugs in next (why should anyone use knowingly broken code).

The point is I don't see any reason to not merge master into next.

So I have zero understanding as to why we shouldn't merge.
If you want, I can elaborate on the benefits.

**Comment by ZedThree** [comment]
Most people want to be using master rather than next. There's actually very few people who both develop and use BOUT++, and so want to be using next. Therefore, we definitely want bug fixes to go into master.

In principle, it would be great if bug fixes went into both master and next. In practice, this means having to open two PRs, one for each branch, and I think most of us just forget to open both. So our policy is for bug fixes to just go straight into master, everything else into next, and then we periodically merge master into next.

After new releases, there's also usually a short period where we catch loads of bugs we didn't notice, so there's a lot of activity for a couple of weeks before it dies down again. So, in order to cut down on noisy commits to next, we can hold off on merging master into next until it dies down (i.e. once we've released the next minor version).

**Comment by dschwoerer** [comment]
So merging without an extra commit would be perfectly fine?

Wouldn't a merge like this then be perfect? No extra commit message for the master to next merge?

**Pull request merged**
