### PR TITLE
LaplaceXY: finite difference option (v4.4)

### PR DESCRIPTION
**Pull request by johnomotani**
Backport of #1789.

### CODE REVIEW

**Comment by ZedThree** [comment]
Not sure why that one test is failing -- it looks like the same bug that was in next, but that was introduced in next. I've restarted it, maybe it was just Travis being odd.

**Comment by johnomotani** [comment]
Ah, don't want to merge `next` in here. I probably should have made separate branches for this PR and #1789... I'll make a separate branch for this backport now.

**Comment by ZedThree** [comment]
Oops, sorry! I didn't realise these were using the same branch!

**Comment by johnomotani** [comment]
My bad, using the same branch was a bad idea in the first place. It look like I can't actually change the branch, so I'll close this and open a new PR with the new branch.

**Pull request closed without merging**
