### PR TITLE
Add FieldPerp location

### PR DESCRIPTION
**Pull request by d7919**
Aimed at addressing #829 

It might also be worth exploring if this might allow us to squash `FieldPerp` into the generated fieldops code now.

Initially marked as a work in progress, as whilst I've (hopefully) added appropriate location code to all the routines in FieldPerp there may be additional places we need to do checks and/or remember to set location on the result.

### CODE REVIEW

**Comment by d7919** [comment]
@johnomotani I think the only places that are left to change/update is in the Laplacian code -- I'm not quite sure how the Laplacian location systems works/what checks we should make. Do you think you'd get chance to have a look at this?

**Comment by johnomotani** [comment]
It should be simple, I can take a look at it :+1: 

Quick summary is: each Laplacian object has a `CELL_LOC location` member that's set in the constructor (it's not a const member at the moment but maybe should be...). All the inputs and outputs should be at `location`. [Having said that, I'm not sure whether `CELL_XLOW` is actually supported properly in the Laplacian solvers...]

**Comment by d7919** [comment]
Thanks @johnomotani

**Comment by johnomotani** [comment]
Just to note: I don't think we have tests for any `Laplacian` with staggered grids. We should make some, and I don't think there's any particular difficulty to convert the existing tests to add a staggered-grid case, but it's a little more work than just adding the location check/set calls that I did in the last commit.

**Pull request merged**
