### PR TITLE
Remove deprecated get/setdata from fields

### PR DESCRIPTION
**Pull request by ZedThree**
Remove the get/setData functions that were deprecated in 4.0

### CODE REVIEW

**Comment by d7919** [comment]
Are there any other deprecated routines that we can remove at this point (e.g. `field2d::?et?array`, `solver::addToRestart`)?

**Comment by ZedThree** [comment]
`addToRestart` is the only one that currently gives me a warning, and I'm not sure how much that's used.

Other deprecated stuff can probably just go too.

**Comment by bendudson** [comment]
I think I'm probably the only one who uses addToRestart, for feedback controller stuff in SD1D and Hermes. I deprecated the function, but can't quite remember what it's supposed to be replaced by...

I think it's a public function so that Solver can call it. What's deprecated is users calling Solver->addToRestart, since restart files are now in PhysicsModel not in Solver.

Perhaps addToRestart could be removed from Solver, and the PhysicsModel function made protected

**Comment by d7919** [comment]
Isn't this PR duplicated in #643 now?

**Comment by dschwoerer** [comment]
* I thought breaking changes would only go to major releases (4.0, 5.0 ...)
* Why is this going directly into 4.1-RC?

**Comment by ZedThree** [comment]
This is just removal of functions that have been marked deprecated since 4.0, which was more than six months ago now. That should be plenty of time for people to remove them from their code.

Removing marked deprecated functions I think counts as cleaning/tidying :)

**Pull request merged**
