### PR TITLE
Switch to CMake in CI and docs

### PR DESCRIPTION
**Pull request by dschwoerer**
Rebase of #2502 

Now without removing configure files - to be done for v5.1.0

### CODE REVIEW

**Comment by dschwoerer** [comment]
Is it intentionally that we now require `fastcov`?

**Comment by ZedThree** [comment]
I think `fastcov` was just easier/faster to use

**Comment by dschwoerer** [comment]
If you get fastcov to work in CI ...

**Review by ZedThree — APPROVED** [review]
LGTM. Couple of suggestions

**Comment by ZedThree** [comment]
Todo before merge:

- [ ] Add deprecation notice to `./configure`
- [ ] Make sure the docs all use cmake by default

**Comment by dschwoerer** [comment]
I updated the docs, however, I haven't tested all commands - so checking would be greatly appreciated.

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
The failing tests are just Fedora, and that was already fixed in next

**Pull request merged**
