### PR TITLE
Visboutit

### PR DESCRIPTION
**Pull request by peternaylor**
3D visualisation using VISiT in Python by Peter Naylor. Examples and manual for cylindrical and toroidal coordinates (both poloidal planes and toroidal planes)

### CODE REVIEW

**Comment by dschwoerer** [comment]
This would need some cleaning (purging the binaries).
It seems to add some quite useful functionality. 
I haven't tested it yet though ...

**Comment by bendudson** [comment]
Yes, I think this definitely is useful but needs tidying. I think Peter (H) started having a look at it a while ago, but maybe never got around to it. Peter Naylor is a bit busy at the moment, but maybe when he's finished his dissertation...

**Comment by bendudson** [comment]
Merged into a branch `peternaylor-Visboutit` so it's not lost. The manual could be merged into the main manual, and the visualisation code is quite self-contained.

**Comment by d7919** [comment]
As this is standalone should this in fact go into a top level repository rather than the main BOUT++ one?

**Comment by bendudson** [comment]
Yes I think that would make sense. There are some other projects which are related to BOUT++ but don't need to go in the main repository such as BOUTgui https://github.com/joe1510/BOUTgui

**Comment by ZedThree** [comment]
Pulled out into stand alone repo: https://github.com/boutproject/VisBoutIt

**Pull request closed without merging**
