### PR TITLE
More warning fixes

### PR DESCRIPTION
**Pull request by dschwoerer**
fixes the unknown pragma warning and also signifcantly reduces the number of warnings, if CHECK is disabled ...

### CODE REVIEW

**Comment by ZedThree** [comment]
The second commit is good, but I'm less sure about the first one. I'm not terribly keen on replacing `#pragma`s with macros. The point about pragmas is that the compiler is supposed to ignore them if it doesn't understand. I think I'd much rather use `-Wno-unknown-pragmas` to disable the warning, even if this means not catching typos in pragmas. The warning could just be enabled when adding new pragmas.

Also, I'm not sure about getting rid of the header guards. I don't think there's any harm in keeping them and there's very little benefit in getting rid of them.

**Comment by dschwoerer** [comment]
About replacing pragmas with macros - I don't think it is extremely bad, but of course it can cause confusion. Therefore if you think that it is not worth to remove the warnings, I am fine with that. I think this solution is still better than having `#ifdef _OPENMP` always in front ...

About using `#pragma once` instead of the `#ifdef` guards: I don't see any advantage in keeping them, but agree that the gain is small, but it results in a cleaner code. I wouldn't remove them in all files in one go, but if I am anyway changing a file, I think it is worth removing them ...

**Comment by d7919** [comment]
One thing to note is that (I think) the pgi compiler doesn't currently support `#pragma once` so keeping the header guards will make it easy for someone to still compile if they really want to use pgi.

**Comment by dschwoerer** [comment]
Thanks, I wasn't aware PGI doesn't support this.
I will use `#ifdef` guards in the future ...
https://en.wikipedia.org/wiki/Pragma_once#Portability

**Comment by ZedThree** [comment]
Yeah, it's annoying. To be honest, I think `pragma once` looks cleaner and
has some advantages, but I think the most portable solution is having both.

**Comment by d7919** [comment]
Yes it's a pain, hopefully they'll change this in the future!

**Comment by bendudson** [comment]
I think this PR has been split, with guards being kept, but warnings about unused arguments being suppressed using UNUSED. Is this PR still needed?

**Comment by bendudson** [comment]
I think this PR is now obsolete

**Pull request closed without merging**
