### PR TITLE
Improve mpich detection

### PR DESCRIPTION
**Pull request by dschwoerer**
Still not good, but it is working again on travis.

### CODE REVIEW

**Comment by dschwoerer** [comment]
The old script causes unintended test skips, see e.g:
https://travis-ci.org/boutproject/BOUT-dev/jobs/373276923#L2547

**Comment by bendudson** [comment]
Thanks David for all your work on this. It seems to be a frustratingly difficult thing to do, find out which MPI implementation we're using. I'm not convinced though that this is a better solution; this is probably my problem but there is too much black magic here. I would prefer to find a more robust method.

**Comment by dschwoerer** [comment]
Please note that this version is working, while the current version seems to be broken. `test-multigrid_laplace` gets currently skipped on the openmpi runs, as it seems to detect that mpich is used.

**Comment by bendudson** [comment]
Appreciated; I guess I don't really understand how this new version works

**Comment by ZedThree** [comment]
My understanding is that we were skipping this test with mpich because there were problems with openmpi. Are those problems now sufficiently resolved that we can just use openmpi and remove this check entirely?

**Comment by dschwoerer** [comment]
Should be clearer now:
https://github.com/boutproject/BOUT-dev/blob/mpich_detection_rebase/tests/requirements/mpich
It also has a fallback - using the help which should contain a link to the project website

**Pull request closed without merging**
