### PR TITLE
New test

### PR DESCRIPTION
**Pull request by dschwoerer**
* checks if solver can solve for field2d
* checks if min/max work as expected
* checks if staggered grids works

### CODE REVIEW

**Comment by ZedThree** [comment]
Given that this is testing three different things, could they be split out into different tests?

**Comment by dschwoerer** [comment]
I don't really want to, as I check with min/max whether the staggered grid works
I don't like throwing errors, so in order to exit smoothly, I just solve for the fields with zero time derivative.
That's why the min/max test, also fails if something other is broken.

**Comment by dschwoerer** [comment]
Should I split this in 3 tests?

I don't really see the point, but if that is required, I could have a go (and basically triple all the code)

**Comment by bendudson** [comment]
I think as long as the test prints a useful error message which says which
part failed then it's ok

**Pull request merged**
