### PR TITLE
Fci slab poloidal grids

### PR DESCRIPTION
**Pull request by bshanahan**
Fixes [Issue 655](https://github.com/boutproject/BOUT-dev/issues/655), ensuring fci_slab works for with the new poloidal grid system.

*also changes pass/fail criteria if the convergence is a nan (default fail instead of pass).  
*only works for y-periodic grids

### CODE REVIEW

**Comment by bendudson** [comment]
Great! Does this pass now, or still failing?

**Comment by bshanahan** [comment]
This passes with grids which are periodic in the y-direction.

**Comment by bshanahan** [comment]
Despite the fact that I've asked for the merge, I'm wondering if this (and indeed [626](https://github.com/boutproject/BOUT-dev/pull/626)) should be merged since it does not converge for non-periodic grids (which was previously the default case).

**Comment by dschwoerer** [comment]
I get this error if I try to run the test case:
```
getmpirun: using the default mpirun -np
Making fci-slab test
Traceback (most recent call last):
  File "./runtest", line 57, in <module>
    field = zb.field.Slab(Bz=0.05, Bzprime=0.1)
TypeError: __init__() got an unexpected keyword argument 'Bzprime'
```

Travis is complaining because there is some requirement for matplotlib ...

**Comment by bshanahan** [comment]
First error: python path needs to lead to the newest zoidberg updates (PR 626) and I can't help with the second one, as I didn't add any matplotlib lines. I think any matplotlib stuff has been there as long as the test has been.

**Comment by ZedThree** [comment]
Looks like only ones that pass are with `--enable-checks`, the rest hang on one of the tests (I'm guessing fci-slab?)

**Comment by bendudson** [comment]
Last merge before 4.1...

**Comment by bshanahan** [comment]
Would approve this but I can't as I've opened this PR (I think).

**Comment by ZedThree** [comment]
I've just changed a bit how matplotlib gets imported, and how plotting functions get disabled if it can't be imported

**Pull request merged**
