### PR TITLE
Fix elm pb example

### PR DESCRIPTION
**Pull request by bendudson**
Compiles and runs, but would like to make sure that it produces a similar result to the BOUT++ 3.1 version. The test case should produce a growth rate which can be compared to the value from ELITE.

Lots of reformatting, to put it into a `PhysicsModel` class. Best viewed with whitespace diff off.

### CODE REVIEW

**Comment by dschwoerer** [comment]
I can assert that this does not give the same result as v3.1

The v3.1 does segfault while trying to write an int.

After adding some debug messages, and adding some missing return statements in datafile, it doesn't crash anymore, but the monitor signals to quit -- without any error ...

**Comment by dschwoerer** [comment]
Same/similar seg fault with v3.0 ...

Compiler is gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by dschwoerer** [comment]
v3.1
early exit with `Monitor signalled to quit. Returning`

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

Not sure when the last time that example actually worked ...

**Comment by bendudson** [comment]
IIRC this is/was a known bug, caused by adding a variable twice to the dump output. Probably the last time it worked was shortly after the last paper to be published using it. 2012? Since then there have been many derivatives and variations on it, but mainly in personal repos or at NERSC.

**Comment by bendudson** [comment]
I think this is good enough to go in for now. It's not tested yet, but it runs and produces similar results (~10%) to previously. I don't know when I will have time to properly test this, and it's better than what's in the repo at the moment.

**Comment by ZedThree** [comment]
LGTM -- do you mind if I just make the three laplacian solvers `unique_ptr`?

**Comment by ZedThree** [comment]
@bendudson ok with 7f93806 - fccfc18?

**Pull request merged**
