### PR TITLE
BOUT++ v5.0.0 release candidate

### PR DESCRIPTION
**Pull request by ZedThree**
A truly monumental PR -- BOUT++ v5 is almost here!

See changelog for list of changes. Still lots of maintainer things to do:

- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc`
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis
    
Before merging PR:

- [x] Update locale translation files
    - `make -C locale update-all`
    - Be aware that this *will* update the timestamps and *possibly*
      reorder file paths in the .po and .pot files
- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change DOI in [`README.md`][README.md] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Check `abidiff` to see if `soname` needs bumping in `makefile`:
- [x] Change version number, removing prerelease tag in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`
    - [x]  [`CMakeLists.txt`][CMakeLists.txt]: `_bout_previous_version`, `_bout_next_version`

After PR is merged:

- [ ] Make tarball: `./configure && make dist`
- [ ] Try to summarise the changes!
- [ ] Make [GitHub Release][gh_release], include change summary **NB:** tag should have
      leading `v`
- [ ] Upload tarball to GitHub Release
- [ ] Upload tarball to Zenodo and publish new version
- [ ] Email BOUT++ User Group mailing list, include change summary
- [ ] Make news post on project website, include change summary
- [ ] Update downloads page
- [ ] PR `master` into `next`
- [ ] Bump version number and add prerelease tag in:
    - [ ]  [`configure.ac`][configure]: `AC_INIT`
    - [ ]  [`CITATION.cff`][citation]: `version`
    - [ ]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [ ]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [ ]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`
    - [ ]  [`CMakeLists.txt`][CMakeLists.txt]: `_bout_previous_version`, `_bout_next_version`

[Doxyfile]: ../manual/doxygen/Doxyfile
[Doxyfile_readthedocs]: ../manual/doxygen/Doxyfile_readthedocs
[citation]: ../CITATION.cff
[configure]: ../configure.ac
[sphinx_conf]: ../manual/sphinx/conf.py
[gcg]: https://github.com/github-changelog-generator/github-changelog-generator
[gh_release]: https://github.com/boutproject/BOUT-dev/releases/new

### CODE REVIEW

**Comment by ZedThree** [comment]
The CMake builds are failing in testing `squashoutput`:

```
Parallel and in two pieces
  0.01078987s rm -f f2.nc
  1.98299599s ./squash -q -q -q
  1.26830053s /home/runner/work/BOUT-dev/BOUT-dev/tests/integrated/test-squash/../../../bin/bout-squashoutput -qdcl 9 data --outputname ../f2.nc
  2.01440334s ./squash -q -q -q restart
  1.30285597s /home/runner/work/BOUT-dev/BOUT-dev/tests/integrated/test-squash/../../../bin/bout-squashoutput -qdcal 9 data --outputname ../f2.nc
  0.09860611s verify f1.nc f2.nc
Traceback (most recent call last):
  File "/home/runner/work/BOUT-dev/BOUT-dev/build/tests/integrated/test-squash/runtest", line 106, in <module>
    verify("f1.nc", "f2.nc")
  File "/home/runner/work/BOUT-dev/BOUT-dev/build/tests/integrated/test-squash/runtest", line 75, in verify
    raise RuntimeError("data mismatch in ", v, err, v1, v2)
RuntimeError: ('data mismatch in ', 'hist_hi', '(): 1 != 0\n', BoutArray(1, dtype=int32), BoutArray(0, dtype=int32))
```

I think this is something to do with the solver iteration count -- @johnomotani any ideas? I think you were looking at this awhile ago. I know it changed in master in 4.4.3

**Comment by bendudson** [comment]
Can we merge the latest `next` branch into `v5.0.0-rc`? I think the only thing remaining is to move the headers (PR #2568)

**Comment by dschwoerer** [comment]
I think #2628 may have uncovered a bug, that breaks the installed version. At least in some cases, so maybe it is worth it to hold of?

**Comment by ZedThree** [comment]
The tool we were using previously for updating the changelog no longer works, so I knocked together a new one.

Looks we have around ~600 merged PRs in this release!

**Comment by ZedThree** [comment]
I think I need to turn off the clang-format/tidy workflows on protected branches

**Comment by ZedThree** [comment]
Ok last few things to do:

- [ ] Make sure version is correct everywhere
- [ ] DOI
- [ ] manually run clang-format

**Comment by ZedThree** [comment]
Ok, all v5.0 PRs merged, housekeeping done -- after almost 5 years, v5 is ready to launch! Release is scheduled for Wednesday the 8th.

The CI is going to show this as failing because the clang-format and clang-tidy actions don't like this branch (protected, so can't push, and _way_ too many files, respectively)

**Comment by bendudson** [comment]
Thank you @ZedThree! And thanks to everyone who has volunteered their time and effort to work on this open source effort. There is still work to do, but I think we can all be proud of what we've created.

**Comment by ZedThree** [comment]
Broken :( Fix incoming though

**Comment by bendudson** [comment]
:( Somewhat ironic. Seems to be something PETSc-related.

**Pull request merged**
