### PR TITLE
Recent minor fixes in master into next

### PR DESCRIPTION
**Pull request by ZedThree**

### CODE REVIEW

**Comment by d7919** [comment]
Shouldn't this bump the version to 4.1.2 if it's a bug fix bundle?

**Comment by dschwoerer** [comment]
shouldn't a bug fix version be independent of this PR?
Master would get released as bug fix, whereas this will not get released before 4.2.0 ...

**Comment by dschwoerer** [comment]
Oh, sorry, didn't realised this was not specific to this PR.

**Comment by ZedThree** [comment]
Once #754 is merged, I'll bump master to 4.1.2 then merge this.

**Pull request merged**
