### PR TITLE
Disable broken tests

### PR DESCRIPTION
**Pull request by dschwoerer**
- [x] Waiting on #1540 
- [x] Reenable fixed test
----------

Running tests which are knowingly broken is a waste of
CPU time. Further, it obfuscates new failures.

With this, the overview [here](https://omadesala.alfa1024.info/~bout-test/) should become useful, as not all branches are red :-)

Also makes detecting breakage like #1355 #1354 easier.

### CODE REVIEW

**Comment by dschwoerer** [comment]
I have opened issues:
#1498 
#1499 
#1500 
#1501 
#1502 
#1503 

I need to recompile petsc, as I updated gfortran ...

**Comment by dschwoerer** [comment]
#1189 is already open.
Same error in petsc 3.4 to 3.9

**Comment by ZedThree** [comment]
- #1189 done
- #1499 done
- #1503 done

**Comment by ZedThree** [comment]
Once #1540 is in, it would be good to update this and get it in

**Comment by dschwoerer** [comment]
Only the still broken ones are disabled now, so should be good for merging

**Pull request merged**
