### PR TITLE
Fix examples so most compile

### PR DESCRIPTION
**Pull request by d7919**
A few examples still don't compile due to features missing from the current library. 

Intend to produce a separate PR that provides an integrated test that just checks we can compile all the examples.

### CODE REVIEW

**Comment by d7919** [comment]
Examples that still don't compile are:

1. blob2d-outerloop -- uses dataiterator linked routines (proposed for removal in #1358)
2. non-local_1d -- uses removed `bindex` struct.
3. uedge-benchmark -- uses removed `bindex` struct.

**Comment by d7919** [comment]
I should note this includes a bug fix in commit a45bc40 which I can pull out if required. This may also need to go into master.

**Comment by d7919** [comment]
Should we fix non-local_1d before merging this?

**Comment by bendudson** [comment]
non-local_1d might need quite a bit more work to tidy up. I have a version of the nonlocal heat transport code from this example in SD1D which works with the latest BOUT++ version: https://github.com/boutproject/SD1D/tree/nonlocal
It might be easiest to just put the SD1D version into BOUT++ examples, or remove non-local_1d from examples.

**Comment by ZedThree** [comment]
+1 for removing non-local_1d, at least for now.

**Pull request merged**
