### PR TITLE
Release V4.3.3

### PR DESCRIPTION
**Pull request by ZedThree**
I will be releasing this tomorrow, unless there are any serious objections!

# Making a New Release of BOUT++

This is checklist of things to do (in order) when making a new
release. This applies equally to both major/minor releases and bugfix
releases

- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc`
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis
    
Before merging PR:

- [x] Update locale translation files
    - `make -C locale update-all`
    - Be aware that this *will* update the timestamps and *possibly*
      reorder file paths in the .po and .pot files
- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Check `abidiff` to see if `soname` needs bumping in `makefile`:
- [x] Change version number in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`

After PR is merged:

- [ ] Make tarball: `make dist`
- [ ] Try to summarise the changes!
- [ ] Make [GitHub Release][gh_release], include change summary **NB:** tag should have
      leading `v`
- [ ] Upload tarball to GitHub Release
- [ ] Upload tarball to Zenodo and publish new version
- [ ] Email BOUT++ User Group mailing list, include change summary
- [ ] Make news post on project website, include change summary
- [ ] PR `master` into `next`

[Doxyfile]: ../manual/doxygen/Doxyfile
[Doxyfile_readthedocs]: ../manual/doxygen/Doxyfile_readthedocs
[citation]: ../CITATION.cff
[configure]: ../configure.ac
[sphinx_conf]: ../manual/sphinx/conf.py
[gcg]: https://github.com/github-changelog-generator/github-changelog-generator
[gh_release]: https://github.com/boutproject/BOUT-dev/releases/new

### CODE REVIEW

**Comment by ZedThree** [comment]
I forgot to update clang-tidy-review and rtd, but they will be fixed in v4.4.0 anyway

**Comment by dschwoerer** [comment]
Hmm, I seem to get some changes from abidiff, comparing 4.3.2 and this branch:
```
Functions changes summary: 4 Removed, 0 Changed, 0 Added functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Function symbols changes summary: 0 Removed, 6 Added function symbols not referenced by debug info
Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

4 Removed functions:

  [D] 'method void DataFormat::writeFieldAttributes(const std::string&, const Field&)'    {_ZN10DataFormat20writeFieldAttributesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK5Field}
  [D] 'method void DataFormat::writeFieldAttributes(const std::string&, const FieldPerp&)'    {_ZN10DataFormat20writeFieldAttributesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK9FieldPerp}
  [D] 'method bool Solver::have_user_precon()'    {_ZN6Solver16have_user_preconEv}
  [D] 'method int Solver::run_precon(BoutReal, BoutReal, BoutReal)'    {_ZN6Solver10run_preconEddd}

6 Added function symbols not referenced by debug info:

  [A] _ZN10DataFormat20writeFieldAttributesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK5Fieldb
  [A] _ZN10DataFormat20writeFieldAttributesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK9FieldPerpb
  [A] _ZN6Solver11hasJacobianEv
  [A] _ZN6Solver11runJacobianEd
  [A] _ZN6Solver17hasPreconditionerEv
  [A] _ZN6Solver17runPreconditionerEddd
```

So we added some extra arguments, and renamed 2 functions - it would be better to bump soname ...

**Comment by ZedThree** [comment]
Oh, I had completely different output. Probably doing something wrong! Ok, will bump the soversion before release

**Comment by dschwoerer** [comment]
I compared the mpich (x86_64) builds from https://copr.fedorainfracloud.org/coprs/davidsch/testing/build/2352175/ with https://koji.fedoraproject.org/koji/buildinfo?buildID=1775943

We should probably fix RTD for the release, so the documentation is build properly?
I think it is quite easy to build docs for a selection of released versions?

**Comment by ZedThree** [comment]
I'll push the RTD fix straight to this branch, along with bumping the soversion to 4.3.3

**Pull request merged**
