### PR TITLE
Version 4.4.1 release

### PR DESCRIPTION
**Pull request by ZedThree**
Just waiting on #2459, and we'll have 4.4.1 out the door before the end of the year!

# Making a New Release of BOUT++

This is checklist of things to do (in order) when making a new
release. This applies equally to both major/minor releases and bugfix
releases

- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc`
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis
    
Before merging PR:

- [x] Update locale translation files
    - `make -C locale update-all`
    - Be aware that this *will* update the timestamps and *possibly*
      reorder file paths in the .po and .pot files
- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Check `abidiff` to see if `soname` needs bumping in `makefile`:
- [x] Change version number in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`

After PR is merged:

- [ ] Make tarball: `./configure && make dist`
- [ ] Try to summarise the changes!
- [ ] Make [GitHub Release][gh_release], include change summary **NB:** tag should have
      leading `v`
- [ ] Upload tarball to GitHub Release
- [ ] Upload tarball to Zenodo and publish new version
- [ ] Email BOUT++ User Group mailing list, include change summary
- [ ] Make news post on project website, include change summary
- [ ] PR `master` into `next`

[Doxyfile]: ../manual/doxygen/Doxyfile
[Doxyfile_readthedocs]: ../manual/doxygen/Doxyfile_readthedocs
[citation]: ../CITATION.cff
[configure]: ../configure.ac
[sphinx_conf]: ../manual/sphinx/conf.py
[gcg]: https://github.com/github-changelog-generator/github-changelog-generator
[gh_release]: https://github.com/boutproject/BOUT-dev/releases/new

### CODE REVIEW

**Comment by ZedThree** [comment]
I've bumped the `SONAME` to 4.4.1, but maybe that wasn't right. Here's `abidiff` with 4.4.0:

```
ELF SONAME changed
Functions changes summary: 0 Removed, 0 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

SONAME changed from 'libbout++.so.4.4.1' to 'libbout++.so.4.4.0'
```

@dschwoerer Should we leave `SONAME` as 4.4.0? Should we actually have set it to 4.4 previously?

**Comment by dschwoerer** [comment]
Yes, please revert to `4.4.0`.  `4.4` has the disadvantage that we probably should increase to `4.5` if there is a change, which would be even more confusing with a potential 4.5.0 release ...

Might be better to switch to a new versioning scheme, and just have sequential numbers, and increase on demand.

Somewhat related, I thought of setting up a CI for checking abidiff, but didn't get around to it yet ...

**Comment by ZedThree** [comment]
This is ready to go, bar #2459. Unfortunately, I'm now off until the new year.
If someone else wants to do the release, the remaining steps are in the top comment, otherwise it will only take me a few minutes.

@bendudson What do you want to do about #2459? I'm happy waiting for that to go in this release if you want.

**Comment by ZedThree** [comment]
@bendudson Please can you rubber-stamp this, and I'll do the post-merge stuff tomorrow? :slightly_smiling_face:

**Review by bendudson — APPROVED** [review]
Please consider this rubber stamped. Thanks for all this @ZedThree !

**Pull request merged**
