### PR TITLE
Save field cell location attributes

### PR DESCRIPTION
**Pull request by bendudson**
The datafile class now sets an attribute "cell_location" for each 2D and 3D field (and vector component).
Fixes issue #736.

The attribute is a string which is the same as the enum name e.g. CELL_CENTRE, CELL_YLOW etc.

To do this, a const map has been added to bout_types.hxx, together with an inline function CELL_LOC_STRING(). This replaces `strLocation` in interpolation.hxx, which used a switch.

Together with PR #770 (saving attributes in NetCDF) and #996 (reads attributes into a BoutArray class), this now works (in test-io):

```
> f3d = collect("f3d")
> f3d.attributes
{'cell_location': 'CELL_CENTRE', 'bout_type': 'Field3D'}
```

Added some checks to `test-io` to check that the cell_location attribute is read correctly.

### CODE REVIEW

**Comment by dschwoerer** [comment]
Support for boutcore's fromCollect will follow when this is merged :+1:

**Comment by johnomotani** [comment]
We'll need to add writing of the Vector3D::location when #994 is merged.

**Comment by bendudson** [comment]
At the moment Vector3D objects are written out as separate components, each of which has a location. If the Vector3D::location is consistent with the (x,y,z) locations then this should be ok I think.

**Comment by johnomotani** [comment]
@bendudson right! yes, that should be fine. Sorry, I forgot how vectors got written.

I added attribute writing for HDF5, and an updated test-io_hdf5 passes, with ``cell_location`` being written correctly.

**Pull request merged**
