### PR TITLE
Redistribute restarts

### PR DESCRIPTION
**Pull request by johnomotani**
Added a redistribute(npes, path, nxpe, output, informat, outformat)
function to boutdata.restart. This collects the data from a set of
old restart files and creates a set of new ones for arbitrary (valid)
npes and nxpe.

### CODE REVIEW

**Comment by JensMadsen** [comment]
Hi John 

Does this mean that I am able to 

1) run a code with 4 processors
2) restart the code with 16 processors? 

Could you add an example line in the python code:-D

**Comment by JensMadsen** [comment]
Works  like a charm. Thanks. Just what I needed :-D

**Comment by JensMadsen** [comment]
Hi John 

I can make the routine work if npeold< npenew? I I redistribute to a smaller number of processors It seems not to work?

**Comment by johnomotani** [comment]
> I can make the routine work if npeold< npenew? I I redistribute to a 
> smaller number of processors It seems not to work?
>

It ought to work, as long as there is a valid split of the grid over 
npenew processors. I only tested very quickly, but going from 4->2 
seemed to work. Does it give an error for you, or just produce wrong output?

**Comment by JensMadsen** [comment]
It just gives wrong output. I provide you with some more details in a minute:-D

**Comment by JensMadsen** [comment]
The fields are just set to constant values.

**Pull request merged**
