### PR TITLE
Compat make.config for make 4.3

### PR DESCRIPTION
**Pull request by dschwoerer**
We are affected by the first of the non-compatible changes in [gnu make 4.3](https://fedoraproject.org/wiki/Changes/MAKE43)

Still waiting on local tests to finish.

Should I add a test on travis for fedora?

### CODE REVIEW

**Comment by ZedThree** [comment]
Urgh, that's a pain. An alternative is to use `$(basename f)`. Personally I find the `${f##*/}` syntax not especially enlightening.

**Comment by dschwoerer** [comment]
Switched to basename. You are right, that is much cleaner, and requieres less fidelling, as e.g. `a/b/c///` is now working as well :+1:

**Comment by ZedThree** [comment]
Thanks for finding and fixing this!

**Comment by dschwoerer** [comment]
Now BOUT++ successfully builds on several arches: https://koji.fedoraproject.org/koji/taskinfo?taskID=42619777

**Pull request merged**
