### PR TITLE
Exclude corner cells in LaplaceXY

### PR DESCRIPTION
**Pull request by ZedThree**
Think this should've been in #1885 maybe. My bad, definitely a downside to breaking #1803 into separate PRs!

This is why half the PR tests are failing. Not sure why the other half are yet

### CODE REVIEW

**Comment by ZedThree** [comment]
Lots of errors on Travis because they decided to handle quotes in environment variables differently for a couple of hours.

**Comment by ZedThree** [comment]
Looks like I also broke test-yupdown

**Comment by johnomotani** [comment]
> Looks like I also broke test-yupdown

I'm looking at that one. There's a small error just on the `ystart` points...

**Comment by ZedThree** [comment]
Fixed, and also fixed and tidied up test-yupdown-weights while I was at it.

**Pull request merged**
