### PR TITLE
Release V4.4.0

### PR DESCRIPTION
**Pull request by ZedThree**
This is _long_ overdue. There's probably still some things we want to backport from `next` into this. Probably getting a bunch of the CMake stuff in is a good idea. @johnomotani Anything you think is missing?

# Making a New Release of BOUT++

This is checklist of things to do (in order) when making a new
release. This applies equally to both major/minor releases and bugfix
releases

- [x] Check there are no open issues/PRs for this milestone
    - Fix or bump to next version
- [x] Make a branch named `vX.Y.Z-rc` (actually just using the `v4.4.0-alpha` branch)
    - The GitHub repo is setup to protect branches named in this style
    - Major and minor release points (`X`/`Y`) should be off
      `next`. Bugfix releases (`Z`) should be off `master`
- [x] Make pull request into `master`
    - Any new bugfixes should be PRs into the RC branch, where
      "bugfixes" can include:
        - silencing warnings
        - improving documentation
        - adding tests
- [x] Run `make check-all`
    - Raise issues for any tests that fail
- Possibly run `clang-tidy`, `clang-check`, `coverity`, etc.
- [x] Review pinned pip package versions for Travis
    
Before merging PR:

- [x] Update locale translation files
    - `make -C locale update-all`
    - Be aware that this *will* update the timestamps and *possibly*
      reorder file paths in the .po and .pot files
- [x] Update [`CHANGELOG.md`][changelog]:
    - Install [`github_changelog_generator`][gcg]
        - Make sure it is at least v1.15!
    - Run like `make changelog LAST_VERSION=vA.B.C RELEASE_BRANCH=master|next`
        - See the docs for how to get the token
        - `RELEASE_BRANCH` might need to be the RC branch to get
          bugfix PRs
    - Check [`CHANGELOG.md`][changelog]!
        - Remove duplicate header/footer
        - Replace extraneous escaping: `\(\)`
- [x] Get list of authors:
    - [x] `git log --format='%aN' | sort | uniq`
    - [x] Compare to list in [`CITATION.cff`][citation], add new authors
- [x] Prep a new Zenodo release:
    - https://doi.org/10.5281/zenodo.1423212
    - "New Version"
    - "Reserve DOI" -> copy DOI
    - Add any new authors
    - Save draft
- [x] Change DOI in [`CITATION.cff`][citation] to new DOI
- [x] Change date-released in [`CITATION.cff`][citation]
- [x] Check `abidiff` to see if `soname` needs bumping in `makefile`:
- [x] Change version number in:
    - [x]  [`configure.ac`][configure]: `AC_INIT`
    - [x]  [`CITATION.cff`][citation]: `version`
    - [x]  [`manual/sphinx/conf.py`][sphinx_conf]: `version` and `release`
    - [x]  [`manual/doxygen/Doxyfile_readthedocs`][Doxyfile_readthedocs]: `PROJECT_NUMBER`
    - [x]  [`manual/doxygen/Doxyfile`][Doxyfile]: `PROJECT_NUMBER`

After PR is merged:

- [ ] Make tarball: `make dist`
- [ ] Try to summarise the changes!
- [ ] Make [GitHub Release][gh_release], include change summary **NB:** tag should have
      leading `v`
- [ ] Upload tarball to GitHub Release
- [ ] Upload tarball to Zenodo and publish new version
- [ ] Email BOUT++ User Group mailing list, include change summary
- [ ] Make news post on project website, include change summary
- [ ] PR `master` into `next`

[Doxyfile]: ../manual/doxygen/Doxyfile
[Doxyfile_readthedocs]: ../manual/doxygen/Doxyfile_readthedocs
[citation]: ../CITATION.cff
[configure]: ../configure.ac
[sphinx_conf]: ../manual/sphinx/conf.py
[gcg]: https://github.com/github-changelog-generator/github-changelog-generator
[gh_release]: https://github.com/boutproject/BOUT-dev/releases/new

### CODE REVIEW

**Comment by johnomotani** [comment]
I don't know of anything else that needs to go in. CMake stuff would be nice, but not essential for me at the moment - happy to leave to 4.4.1 or even (if it's going to be much work) 5.0.

**Comment by dschwoerer** [comment]
Would it make sense to do a v4.3.3 release as well?

There has been a surprisingly large number of commits since v4.3.2 to master:

https://github.com/boutproject/BOUT-dev/commits/master?after=45c3574b66614079252c6c8f4f5645a4a2a98ab4+69&branch=master

**Comment by ZedThree** [comment]
Thanks, a v4.3.3 release is a good idea! There's more commits than I thought. That release shouldn't be too hard, I'll get it started now.

---

This branch needs:

- [ ] Fix for readthedocs sphinx/breathe issue
- [ ] clang-tidy-review version bump

Plus the following tests are failing:
- [ ] MMS/spatial/diffusion
- [ ] test-gyro
- [ ] test-slepc-solver
- [ ] test-squash
- [ ] test-laplacexy

**Comment by ZedThree** [comment]
`test-gyro` and `test-slepc-solver` don't like `--enable-sigfpe`, I guess because they involve operators that don't either fill in the guards, or explicitly set them to NaN. It would be nice to fix the tests so that wasn't a problem, but that's not a blocker.

**Comment by ZedThree** [comment]
`test-laplacexy` is still failing: `LaplaceXY failed to converge. Reason -5`. This is `KSP_DIVERGED_BREAKDOWN` "generic breakdown in method".

This on the first check:

```
mpiexec -np 8 ./test-laplacexy laplacexy:core_bndry_dirichlet=true laplacexy:pf_bndry_dirichlet=true laplacexy:y_bndry=dirichlet f:bndry_xin=dirichlet f:bndry_xout=dirichlet f:bndry_yup=dirichlet f:bndry_ydown=dirichlet mesh:g12=0.
```

Adding `laplacexy:pctype=hypre` makes it pass.

**Comment by johnomotani** [comment]
> `test-laplacexy` is still failing: `LaplaceXY failed to converge. Reason -5`. This is `KSP_DIVERGED_BREAKDOWN` "generic breakdown in method".
> 
> This on the first check:
> 
> ```
> mpiexec -np 8 ./test-laplacexy laplacexy:core_bndry_dirichlet=true laplacexy:pf_bndry_dirichlet=true laplacexy:y_bndry=dirichlet f:bndry_xin=dirichlet f:bndry_xout=dirichlet f:bndry_yup=dirichlet f:bndry_ydown=dirichlet mesh:g12=0.
> ```
> 
> Adding `laplacexy:pctype=hypre` makes it pass.

As far as I remember, when I was writing this test originally, I tried to use `laplacexy:pctype=sor` or `laplacexy:pctype=user` in as many places as possible so the test would do as much as possible when hypre wasn't available. The non-hypre options didn't converge very well though, and I'm not surprised that another case needs hypre to pass. I think it's fine to just change this one to use hypre (I think there was some mechanism for skipping tests that require hypre if hypre's not available?).

**Comment by ZedThree** [comment]
It looks like if I set `pctype=sor` or `hypre` for all the cases that don't have `pctype` set, they pass. It looks like `sor` is always available, so might make sense to make that the default if `hypre` isn't available?

**Comment by johnomotani** [comment]
Yes, I think `sor` is always available, so makes sense to set as the default if it's working.

**Comment by ZedThree** [comment]
Ok, hopefully now backported most of the interesting, but backwards compatible!, build system improvements from `next`. This means at least that v4.4 and v5 will have the same flag names for CMake, as well as benefiting from things like downloading netCDF-cxx4 and SUNDIALS as part of the build process.

**Comment by ZedThree** [comment]
Of the merged PRs with the "backport candidate" label (), there's a few that haven't been ported yet.

I'm going to (attempt to!) port the following:

- [ ] Allow PETSc options to be passed from BOUT.inp #1795
- [ ] Adding an adaptive, arbitrary order, Adams-Bashforth solver #1846
- [ ] Add Mesh::getRegion<T> for use in generic code #1890
- [ ] Rename death tests according to gtest recommendations #1891
- [ ] Fixes for staggering in lapd-drift example #1925
- [ ] Fix segfaults from PvodeSolver #1926
- [ ] Add location checks to Div_par_K_Grad_par #2038
- [ ] Fix some HDF5 related issues and add Mesh::getLocal{X,Y,Z}Index #2102
- [ ] Add ability to use FieldPerp in Options #2152 (maybe)
- [ ] Fix shiftOutput #2157
- [ ] Bump boutdata, boututils versions #2335

I'm not going to port these:

- Minor Travis fixes and job names #1942 -- no need!
- Parallel cyclic reduction #2330 -- still has bugs

**Comment by ZedThree** [comment]
Note, given the number of these PRs, I'll probably end up rubber-stamping them. I'll leave each one open for a day or two so people can comment, but otherwise I will use admin powers to merge into this branch.

**Comment by ZedThree** [comment]
clang-tidy does _not_ like the uuid header. Wish I'd added it to an ignore list!

**Comment by ZedThree** [comment]
This is now ready for release!

**Review by johnomotani — APPROVED** [review]
Rubber stamping... Hopefully we reviewed all the PRs, so there's no need to review these changes carefully!

**Comment by ZedThree** [comment]
Thanks @johnomotani !

I'm not sure why the tests failed, looks like a Github error.

**Pull request merged**
